// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gameplay/v1/rpc_game_service.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamType int32

const (
	StreamType_STREAM_TYPE_UNSPECIFIED     StreamType = 0
	StreamType_STREAM_TYPE_GAME_EVENTS     StreamType = 1
	StreamType_STREAM_TYPE_DRAWING_UPDATES StreamType = 2
)

// Enum value maps for StreamType.
var (
	StreamType_name = map[int32]string{
		0: "STREAM_TYPE_UNSPECIFIED",
		1: "STREAM_TYPE_GAME_EVENTS",
		2: "STREAM_TYPE_DRAWING_UPDATES",
	}
	StreamType_value = map[string]int32{
		"STREAM_TYPE_UNSPECIFIED":     0,
		"STREAM_TYPE_GAME_EVENTS":     1,
		"STREAM_TYPE_DRAWING_UPDATES": 2,
	}
)

func (x StreamType) Enum() *StreamType {
	p := new(StreamType)
	*p = x
	return p
}

func (x StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_gameplay_v1_rpc_game_service_proto_enumTypes[0].Descriptor()
}

func (StreamType) Type() protoreflect.EnumType {
	return &file_gameplay_v1_rpc_game_service_proto_enumTypes[0]
}

func (x StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamType.Descriptor instead.
func (StreamType) EnumDescriptor() ([]byte, []int) {
	return file_gameplay_v1_rpc_game_service_proto_rawDescGZIP(), []int{0}
}

type ReplayGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	StreamType    StreamType             `protobuf:"varint,3,opt,name=stream_type,json=streamType,proto3,enum=gameplay.v1.StreamType" json:"stream_type,omitempty"`
	After         string                 `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayGameRequest) Reset() {
	*x = ReplayGameRequest{}
	mi := &file_gameplay_v1_rpc_game_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayGameRequest) ProtoMessage() {}

func (x *ReplayGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameplay_v1_rpc_game_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayGameRequest.ProtoReflect.Descriptor instead.
func (*ReplayGameRequest) Descriptor() ([]byte, []int) {
	return file_gameplay_v1_rpc_game_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayGameRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ReplayGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ReplayGameRequest) GetStreamType() StreamType {
	if x != nil {
		return x.StreamType
	}
	return StreamType_STREAM_TYPE_UNSPECIFIED
}

func (x *ReplayGameRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ReplayGameRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReplayGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ReplayMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	LastId        string                 `protobuf:"bytes,3,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayGameResponse) Reset() {
	*x = ReplayGameResponse{}
	mi := &file_gameplay_v1_rpc_game_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayGameResponse) ProtoMessage() {}

func (x *ReplayGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameplay_v1_rpc_game_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayGameResponse.ProtoReflect.Descriptor instead.
func (*ReplayGameResponse) Descriptor() ([]byte, []int) {
	return file_gameplay_v1_rpc_game_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReplayGameResponse) GetMessages() []*ReplayMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ReplayGameResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ReplayGameResponse) GetLastId() string {
	if x != nil {
		return x.LastId
	}
	return ""
}

type ReplayMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StreamType    StreamType             `protobuf:"varint,4,opt,name=stream_type,json=streamType,proto3,enum=gameplay.v1.StreamType" json:"stream_type,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayMessage) Reset() {
	*x = ReplayMessage{}
	mi := &file_gameplay_v1_rpc_game_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayMessage) ProtoMessage() {}

func (x *ReplayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gameplay_v1_rpc_game_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayMessage.ProtoReflect.Descriptor instead.
func (*ReplayMessage) Descriptor() ([]byte, []int) {
	return file_gameplay_v1_rpc_game_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReplayMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplayMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReplayMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ReplayMessage) GetStreamType() StreamType {
	if x != nil {
		return x.StreamType
	}
	return StreamType_STREAM_TYPE_UNSPECIFIED
}

func (x *ReplayMessage) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReplayMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_gameplay_v1_rpc_game_service_proto protoreflect.FileDescriptor

const file_gameplay_v1_rpc_game_service_proto_rawDesc = "" +
	"\n" +
	"\"gameplay/v1/rpc_game_service.proto\x12\vgameplay.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x01\n" +
	"\x11ReplayGameRequest\x12(\n" +
	"\tserver_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\bserverId\x12$\n" +
	"\agame_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06gameId\x12@\n" +
	"\vstream_type\x18\x03 \x01(\x0e2\x17.gameplay.v1.StreamTypeB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"streamType\x12\x14\n" +
	"\x05after\x18\x04 \x01(\tR\x05after\x12 \n" +
	"\x05limit\x18\x05 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\x05limit\"\x80\x01\n" +
	"\x12ReplayGameResponse\x126\n" +
	"\bmessages\x18\x01 \x03(\v2\x1a.gameplay.v1.ReplayMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x17\n" +
	"\alast_id\x18\x03 \x01(\tR\x06lastId\"\x81\x02\n" +
	"\rReplayMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x128\n" +
	"\vstream_type\x18\x04 \x01(\x0e2\x17.gameplay.v1.StreamTypeR\n" +
	"streamType\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId*g\n" +
	"\n" +
	"StreamType\x12\x1b\n" +
	"\x17STREAM_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17STREAM_TYPE_GAME_EVENTS\x10\x01\x12\x1f\n" +
	"\x1bSTREAM_TYPE_DRAWING_UPDATES\x10\x02B\xab\x01\n" +
	"\x0fcom.gameplay.v1B\x13RpcGameServiceProtoP\x01Z6github.com/spazzle-io/spazzle-api/services/gameplay/pb\xa2\x02\x03GXX\xaa\x02\vGameplay.V1\xca\x02\vGameplay\\V1\xe2\x02\x17Gameplay\\V1\\GPBMetadata\xea\x02\fGameplay::V1b\x06proto3"

var (
	file_gameplay_v1_rpc_game_service_proto_rawDescOnce sync.Once
	file_gameplay_v1_rpc_game_service_proto_rawDescData []byte
)

func file_gameplay_v1_rpc_game_service_proto_rawDescGZIP() []byte {
	file_gameplay_v1_rpc_game_service_proto_rawDescOnce.Do(func() {
		file_gameplay_v1_rpc_game_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gameplay_v1_rpc_game_service_proto_rawDesc), len(file_gameplay_v1_rpc_game_service_proto_rawDesc)))
	})
	return file_gameplay_v1_rpc_game_service_proto_rawDescData
}

var file_gameplay_v1_rpc_game_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gameplay_v1_rpc_game_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gameplay_v1_rpc_game_service_proto_goTypes = []any{
	(StreamType)(0),               // 0: gameplay.v1.StreamType
	(*ReplayGameRequest)(nil),     // 1: gameplay.v1.ReplayGameRequest
	(*ReplayGameResponse)(nil),    // 2: gameplay.v1.ReplayGameResponse
	(*ReplayMessage)(nil),         // 3: gameplay.v1.ReplayMessage
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
}
var file_gameplay_v1_rpc_game_service_proto_depIdxs = []int32{
	0, // 0: gameplay.v1.ReplayGameRequest.stream_type:type_name -> gameplay.v1.StreamType
	3, // 1: gameplay.v1.ReplayGameResponse.messages:type_name -> gameplay.v1.ReplayMessage
	4, // 2: gameplay.v1.ReplayMessage.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: gameplay.v1.ReplayMessage.stream_type:type_name -> gameplay.v1.StreamType
	5, // 4: gameplay.v1.ReplayMessage.payload:type_name -> google.protobuf.Struct
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gameplay_v1_rpc_game_service_proto_init() }
func file_gameplay_v1_rpc_game_service_proto_init() {
	if File_gameplay_v1_rpc_game_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gameplay_v1_rpc_game_service_proto_rawDesc), len(file_gameplay_v1_rpc_game_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gameplay_v1_rpc_game_service_proto_goTypes,
		DependencyIndexes: file_gameplay_v1_rpc_game_service_proto_depIdxs,
		EnumInfos:         file_gameplay_v1_rpc_game_service_proto_enumTypes,
		MessageInfos:      file_gameplay_v1_rpc_game_service_proto_msgTypes,
	}.Build()
	File_gameplay_v1_rpc_game_service_proto = out.File
	file_gameplay_v1_rpc_game_service_proto_goTypes = nil
	file_gameplay_v1_rpc_game_service_proto_depIdxs = nil
}
