// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gameplay/v1/service_gameplay.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gameplay_v1_service_gameplay_proto protoreflect.FileDescriptor

const file_gameplay_v1_service_gameplay_proto_rawDesc = "" +
	"\n" +
	"\"gameplay/v1/service_gameplay.proto\x12\vgameplay.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a$gameplay/v1/rpc_server_service.proto\x1a*gameplay/v1/rpc_server_admin_service.proto\x1a\"gameplay/v1/rpc_word_service.proto\x1a\"gameplay/v1/rpc_game_service.proto2\xec\f\n" +
	"\rServerService\x12\x9d\x01\n" +
	"\fCreateServer\x12 .gameplay.v1.CreateServerRequest\x1a!.gameplay.v1.CreateServerResponse\"H\x92A2\x12\rCreate server\x1a\x13Create a new serverb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\r:\x01*\"\b/servers\x12\x84\x01\n" +
	"\tGetServer\x12\x1d.gameplay.v1.GetServerRequest\x1a\x1e.gameplay.v1.GetServerResponse\"8\x92A \x12\n" +
	"Get server\x1a\x10Get server by idb\x00\x82\xd3\xe4\x93\x02\x0f\x12\r/servers/{id}\x12\xa7\x01\n" +
	"\x0fGetServerByName\x12#.gameplay.v1.GetServerByNameRequest\x1a$.gameplay.v1.GetServerByNameResponse\"I\x92A'\x12\x12Get server by name\x1a\x0fGet server nameb\x00\x82\xd3\xe4\x93\x02\x19\x12\x17/servers/by-name/{name}\x12\x87\x01\n" +
	"\vListServers\x12\x1f.gameplay.v1.ListServersRequest\x1a .gameplay.v1.ListServersResponse\"5\x92A\"\x12\fList servers\x1a\x10List all serversb\x00\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/servers\x12\xcf\x01\n" +
	"\x0fListUserServers\x12#.gameplay.v1.ListUserServersRequest\x1a$.gameplay.v1.ListUserServersResponse\"q\x92AL\x12\x11List user servers\x1a5List servers for which a user has elevated privilegesb\x00\x82\xd3\xe4\x93\x02\x1c\x12\x1a/servers/by-user/{user_id}\x12\x8c\x02\n" +
	"\x18GetUserServerPermissions\x12,.gameplay.v1.GetUserServerPermissionsRequest\x1a-.gameplay.v1.GetUserServerPermissionsResponse\"\x92\x01\x92A]\x12\x1fGet a user's server permissions\x1a8Check whether a user has elevated privileges on a serverb\x00\x82\xd3\xe4\x93\x02,\x12*/servers/{server_id}/permissions/{user_id}\x12\xa3\x01\n" +
	"\fUpdateServer\x12 .gameplay.v1.UpdateServerRequest\x1a!.gameplay.v1.UpdateServerResponse\"N\x92A,\x12\rUpdate server\x1a\rUpdate serverb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/servers/{server_id}\x12\xb0\x01\n" +
	"\rArchiveServer\x12!.gameplay.v1.ArchiveServerRequest\x1a\".gameplay.v1.ArchiveServerResponse\"X\x92A.\x12\x0eArchive server\x1a\x0eArchive serverb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/servers/{server_id}/archive\x12\xc5\x01\n" +
	"\x11GetServerTreasury\x12%.gameplay.v1.GetServerTreasuryRequest\x1a&.gameplay.v1.GetServerTreasuryResponse\"a\x92A9\x12\x13Get server treasury\x1a Get server treasury by server idb\x00\x82\xd3\xe4\x93\x02\x1f\x12\x1d/servers/{server_id}/treasury2\x88\x05\n" +
	"\x12ServerAdminService\x12\xca\x01\n" +
	"\x0eAddServerAdmin\x12\".gameplay.v1.AddServerAdminRequest\x1a#.gameplay.v1.AddServerAdminResponse\"o\x92AF\x12\x1aAdd a server administrator\x1a\x1aAdd a server administratorb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/servers/{server_id}/admins\x12\xc1\x01\n" +
	"\x10ListServerAdmins\x12$.gameplay.v1.ListServerAdminsRequest\x1a%.gameplay.v1.ListServerAdminsResponse\"`\x92A:\x12\x1aList server administrators\x1a\x1aList server administratorsb\x00\x82\xd3\xe4\x93\x02\x1d\x12\x1b/servers/{server_id}/admins\x12\xe0\x01\n" +
	"\x11RemoveServerAdmin\x12%.gameplay.v1.RemoveServerAdminRequest\x1a&.gameplay.v1.RemoveServerAdminResponse\"|\x92AL\x12\x1dRemove a server administrator\x1a\x1dRemove a server administratorb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02'*%/servers/{server_id}/admins/{user_id}2\xe4\a\n" +
	"\vWordService\x12\xb9\x01\n" +
	"\bAddWords\x12\x1c.gameplay.v1.AddWordsRequest\x1a\x1d.gameplay.v1.AddWordsResponse\"p\x92AH\x12\x1bAdd words to a given server\x1a\x1bAdd words to a given serverb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/servers/{server_id}/words\x12\xd5\x01\n" +
	"\x0eGetRandomWords\x12\".gameplay.v1.GetRandomWordsRequest\x1a#.gameplay.v1.GetRandomWordsResponse\"z\x92AN\x12\x1eGet random words from a server\x1a\x1eGet random words from a serverb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02#\x12!/servers/{server_id}/words:random\x12\xa5\x01\n" +
	"\tListWords\x12\x1d.gameplay.v1.ListWordsRequest\x1a\x1e.gameplay.v1.ListWordsResponse\"Y\x92A4\x12\x11List server words\x1a\x11List server wordsb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x1c\x12\x1a/servers/{server_id}/words\x12\xc7\x01\n" +
	"\vRemoveWords\x12\x1f.gameplay.v1.RemoveWordsRequest\x1a .gameplay.v1.RemoveWordsResponse\"u\x92AF\x12\x1aRemove words from a server\x1a\x1aRemove words from a serverb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02&:\x01*\"!/servers/{server_id}/words:remove\x12\xce\x01\n" +
	"\x0eRemoveAllWords\x12\".gameplay.v1.RemoveAllWordsRequest\x1a#.gameplay.v1.RemoveAllWordsResponse\"s\x92AN\x12\x1eRemove all words from a server\x1a\x1eRemove all words from a serverb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\x1c*\x1a/servers/{server_id}/words2\x8c\x0f\n" +
	"\vGameService\x12\xcc\x01\n" +
	"\x0eGetCurrentGame\x12\".gameplay.v1.GetCurrentGameRequest\x1a#.gameplay.v1.GetCurrentGameResponse\"q\x92AD\x12\x10Get current game\x1a.Get live game state for a server's active gameb\x00\x82\xd3\xe4\x93\x02$\x12\"/servers/{server_id}/games/current\x12\x8f\x01\n" +
	"\aGetGame\x12\x1b.gameplay.v1.GetGameRequest\x1a\x1c.gameplay.v1.GetGameResponse\"I\x92A.\x12\bGet game\x1a Get details for a completed gameb\x00\x82\xd3\xe4\x93\x02\x12\x12\x10/games/{game_id}\x12\xd0\x01\n" +
	"\x12GetGameLeaderboard\x12&.gameplay.v1.GetGameLeaderboardRequest\x1a'.gameplay.v1.GetGameLeaderboardResponse\"i\x92AB\x12\x14Get game leaderboard\x1a(Get player rankings for a completed gameb\x00\x82\xd3\xe4\x93\x02\x1e\x12\x1c/games/{game_id}/leaderboard\x12\xbb\x01\n" +
	"\x0fListServerGames\x12#.gameplay.v1.ListServerGamesRequest\x1a$.gameplay.v1.ListServerGamesResponse\"]\x92A8\x12\x11List server games\x1a!List completed games for a serverb\x00\x82\xd3\xe4\x93\x02\x1c\x12\x1a/servers/{server_id}/games\x12\xd0\x01\n" +
	"\x14GetServerLeaderboard\x12(.gameplay.v1.GetServerLeaderboardRequest\x1a).gameplay.v1.GetServerLeaderboardResponse\"c\x92A8\x12\x16Get server leaderboard\x1a\x1cGet top players for a serverb\x00\x82\xd3\xe4\x93\x02\"\x12 /servers/{server_id}/leaderboard\x12\xbd\x01\n" +
	"\rListUserGames\x12!.gameplay.v1.ListUserGamesRequest\x1a\".gameplay.v1.ListUserGamesResponse\"e\x92AD\x12\x0fList user games\x1a/List games a user has played across all serversb\x00\x82\xd3\xe4\x93\x02\x18\x12\x16/users/{user_id}/games\x12\xc2\x01\n" +
	"\x14GetGlobalLeaderboard\x12(.gameplay.v1.GetGlobalLeaderboardRequest\x1a).gameplay.v1.GetGlobalLeaderboardResponse\"U\x92A>\x12\x16Get global leaderboard\x1a\"Get top players across all serversb\x00\x82\xd3\xe4\x93\x02\x0e\x12\f/leaderboard\x12\xaf\x01\n" +
	"\fGetUserStats\x12 .gameplay.v1.GetUserStatsRequest\x1a!.gameplay.v1.GetUserStatsResponse\"Z\x92A9\x12\x0eGet user stats\x1a%Get a user's all-time game statisticsb\x00\x82\xd3\xe4\x93\x02\x18\x12\x16/users/{user_id}/stats\x12\xa5\x01\n" +
	"\bJoinGame\x12\x1c.gameplay.v1.JoinGameRequest\x1a\x1d.gameplay.v1.JoinGameResponse\"\\\x92A/\x12\tJoin game\x1a Join the active game on a serverb\x00\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/servers/{server_id}/games:join\x12\xd8\x01\n" +
	"\n" +
	"ReplayGame\x12\x1e.gameplay.v1.ReplayGameRequest\x1a\x1f.gameplay.v1.ReplayGameResponse\"\x88\x01\x92AR\x12\vReplay game\x1aAReplay game events from a specific point in a game's event streamb\x00\x82\xd3\xe4\x93\x02-\x12+/servers/{server_id}/games/{game_id}/replayB\xcf\x02\x92A\x9f\x01\x124\n" +
	"\x10Gameplay Service\"\x1d\n" +
	"\aSpazzle\x12\x12https://spazzle.io2\x010ZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\n" +
	"\x0fcom.gameplay.v1B\x14ServiceGameplayProtoP\x01Z6github.com/spazzle-io/spazzle-api/services/gameplay/pb\xa2\x02\x03GXX\xaa\x02\vGameplay.V1\xca\x02\vGameplay\\V1\xe2\x02\x17Gameplay\\V1\\GPBMetadata\xea\x02\fGameplay::V1b\x06proto3"

var file_gameplay_v1_service_gameplay_proto_goTypes = []any{
	(*CreateServerRequest)(nil),              // 0: gameplay.v1.CreateServerRequest
	(*GetServerRequest)(nil),                 // 1: gameplay.v1.GetServerRequest
	(*GetServerByNameRequest)(nil),           // 2: gameplay.v1.GetServerByNameRequest
	(*ListServersRequest)(nil),               // 3: gameplay.v1.ListServersRequest
	(*ListUserServersRequest)(nil),           // 4: gameplay.v1.ListUserServersRequest
	(*GetUserServerPermissionsRequest)(nil),  // 5: gameplay.v1.GetUserServerPermissionsRequest
	(*UpdateServerRequest)(nil),              // 6: gameplay.v1.UpdateServerRequest
	(*ArchiveServerRequest)(nil),             // 7: gameplay.v1.ArchiveServerRequest
	(*GetServerTreasuryRequest)(nil),         // 8: gameplay.v1.GetServerTreasuryRequest
	(*AddServerAdminRequest)(nil),            // 9: gameplay.v1.AddServerAdminRequest
	(*ListServerAdminsRequest)(nil),          // 10: gameplay.v1.ListServerAdminsRequest
	(*RemoveServerAdminRequest)(nil),         // 11: gameplay.v1.RemoveServerAdminRequest
	(*AddWordsRequest)(nil),                  // 12: gameplay.v1.AddWordsRequest
	(*GetRandomWordsRequest)(nil),            // 13: gameplay.v1.GetRandomWordsRequest
	(*ListWordsRequest)(nil),                 // 14: gameplay.v1.ListWordsRequest
	(*RemoveWordsRequest)(nil),               // 15: gameplay.v1.RemoveWordsRequest
	(*RemoveAllWordsRequest)(nil),            // 16: gameplay.v1.RemoveAllWordsRequest
	(*GetCurrentGameRequest)(nil),            // 17: gameplay.v1.GetCurrentGameRequest
	(*GetGameRequest)(nil),                   // 18: gameplay.v1.GetGameRequest
	(*GetGameLeaderboardRequest)(nil),        // 19: gameplay.v1.GetGameLeaderboardRequest
	(*ListServerGamesRequest)(nil),           // 20: gameplay.v1.ListServerGamesRequest
	(*GetServerLeaderboardRequest)(nil),      // 21: gameplay.v1.GetServerLeaderboardRequest
	(*ListUserGamesRequest)(nil),             // 22: gameplay.v1.ListUserGamesRequest
	(*GetGlobalLeaderboardRequest)(nil),      // 23: gameplay.v1.GetGlobalLeaderboardRequest
	(*GetUserStatsRequest)(nil),              // 24: gameplay.v1.GetUserStatsRequest
	(*JoinGameRequest)(nil),                  // 25: gameplay.v1.JoinGameRequest
	(*ReplayGameRequest)(nil),                // 26: gameplay.v1.ReplayGameRequest
	(*CreateServerResponse)(nil),             // 27: gameplay.v1.CreateServerResponse
	(*GetServerResponse)(nil),                // 28: gameplay.v1.GetServerResponse
	(*GetServerByNameResponse)(nil),          // 29: gameplay.v1.GetServerByNameResponse
	(*ListServersResponse)(nil),              // 30: gameplay.v1.ListServersResponse
	(*ListUserServersResponse)(nil),          // 31: gameplay.v1.ListUserServersResponse
	(*GetUserServerPermissionsResponse)(nil), // 32: gameplay.v1.GetUserServerPermissionsResponse
	(*UpdateServerResponse)(nil),             // 33: gameplay.v1.UpdateServerResponse
	(*ArchiveServerResponse)(nil),            // 34: gameplay.v1.ArchiveServerResponse
	(*GetServerTreasuryResponse)(nil),        // 35: gameplay.v1.GetServerTreasuryResponse
	(*AddServerAdminResponse)(nil),           // 36: gameplay.v1.AddServerAdminResponse
	(*ListServerAdminsResponse)(nil),         // 37: gameplay.v1.ListServerAdminsResponse
	(*RemoveServerAdminResponse)(nil),        // 38: gameplay.v1.RemoveServerAdminResponse
	(*AddWordsResponse)(nil),                 // 39: gameplay.v1.AddWordsResponse
	(*GetRandomWordsResponse)(nil),           // 40: gameplay.v1.GetRandomWordsResponse
	(*ListWordsResponse)(nil),                // 41: gameplay.v1.ListWordsResponse
	(*RemoveWordsResponse)(nil),              // 42: gameplay.v1.RemoveWordsResponse
	(*RemoveAllWordsResponse)(nil),           // 43: gameplay.v1.RemoveAllWordsResponse
	(*GetCurrentGameResponse)(nil),           // 44: gameplay.v1.GetCurrentGameResponse
	(*GetGameResponse)(nil),                  // 45: gameplay.v1.GetGameResponse
	(*GetGameLeaderboardResponse)(nil),       // 46: gameplay.v1.GetGameLeaderboardResponse
	(*ListServerGamesResponse)(nil),          // 47: gameplay.v1.ListServerGamesResponse
	(*GetServerLeaderboardResponse)(nil),     // 48: gameplay.v1.GetServerLeaderboardResponse
	(*ListUserGamesResponse)(nil),            // 49: gameplay.v1.ListUserGamesResponse
	(*GetGlobalLeaderboardResponse)(nil),     // 50: gameplay.v1.GetGlobalLeaderboardResponse
	(*GetUserStatsResponse)(nil),             // 51: gameplay.v1.GetUserStatsResponse
	(*JoinGameResponse)(nil),                 // 52: gameplay.v1.JoinGameResponse
	(*ReplayGameResponse)(nil),               // 53: gameplay.v1.ReplayGameResponse
}
var file_gameplay_v1_service_gameplay_proto_depIdxs = []int32{
	0,  // 0: gameplay.v1.ServerService.CreateServer:input_type -> gameplay.v1.CreateServerRequest
	1,  // 1: gameplay.v1.ServerService.GetServer:input_type -> gameplay.v1.GetServerRequest
	2,  // 2: gameplay.v1.ServerService.GetServerByName:input_type -> gameplay.v1.GetServerByNameRequest
	3,  // 3: gameplay.v1.ServerService.ListServers:input_type -> gameplay.v1.ListServersRequest
	4,  // 4: gameplay.v1.ServerService.ListUserServers:input_type -> gameplay.v1.ListUserServersRequest
	5,  // 5: gameplay.v1.ServerService.GetUserServerPermissions:input_type -> gameplay.v1.GetUserServerPermissionsRequest
	6,  // 6: gameplay.v1.ServerService.UpdateServer:input_type -> gameplay.v1.UpdateServerRequest
	7,  // 7: gameplay.v1.ServerService.ArchiveServer:input_type -> gameplay.v1.ArchiveServerRequest
	8,  // 8: gameplay.v1.ServerService.GetServerTreasury:input_type -> gameplay.v1.GetServerTreasuryRequest
	9,  // 9: gameplay.v1.ServerAdminService.AddServerAdmin:input_type -> gameplay.v1.AddServerAdminRequest
	10, // 10: gameplay.v1.ServerAdminService.ListServerAdmins:input_type -> gameplay.v1.ListServerAdminsRequest
	11, // 11: gameplay.v1.ServerAdminService.RemoveServerAdmin:input_type -> gameplay.v1.RemoveServerAdminRequest
	12, // 12: gameplay.v1.WordService.AddWords:input_type -> gameplay.v1.AddWordsRequest
	13, // 13: gameplay.v1.WordService.GetRandomWords:input_type -> gameplay.v1.GetRandomWordsRequest
	14, // 14: gameplay.v1.WordService.ListWords:input_type -> gameplay.v1.ListWordsRequest
	15, // 15: gameplay.v1.WordService.RemoveWords:input_type -> gameplay.v1.RemoveWordsRequest
	16, // 16: gameplay.v1.WordService.RemoveAllWords:input_type -> gameplay.v1.RemoveAllWordsRequest
	17, // 17: gameplay.v1.GameService.GetCurrentGame:input_type -> gameplay.v1.GetCurrentGameRequest
	18, // 18: gameplay.v1.GameService.GetGame:input_type -> gameplay.v1.GetGameRequest
	19, // 19: gameplay.v1.GameService.GetGameLeaderboard:input_type -> gameplay.v1.GetGameLeaderboardRequest
	20, // 20: gameplay.v1.GameService.ListServerGames:input_type -> gameplay.v1.ListServerGamesRequest
	21, // 21: gameplay.v1.GameService.GetServerLeaderboard:input_type -> gameplay.v1.GetServerLeaderboardRequest
	22, // 22: gameplay.v1.GameService.ListUserGames:input_type -> gameplay.v1.ListUserGamesRequest
	23, // 23: gameplay.v1.GameService.GetGlobalLeaderboard:input_type -> gameplay.v1.GetGlobalLeaderboardRequest
	24, // 24: gameplay.v1.GameService.GetUserStats:input_type -> gameplay.v1.GetUserStatsRequest
	25, // 25: gameplay.v1.GameService.JoinGame:input_type -> gameplay.v1.JoinGameRequest
	26, // 26: gameplay.v1.GameService.ReplayGame:input_type -> gameplay.v1.ReplayGameRequest
	27, // 27: gameplay.v1.ServerService.CreateServer:output_type -> gameplay.v1.CreateServerResponse
	28, // 28: gameplay.v1.ServerService.GetServer:output_type -> gameplay.v1.GetServerResponse
	29, // 29: gameplay.v1.ServerService.GetServerByName:output_type -> gameplay.v1.GetServerByNameResponse
	30, // 30: gameplay.v1.ServerService.ListServers:output_type -> gameplay.v1.ListServersResponse
	31, // 31: gameplay.v1.ServerService.ListUserServers:output_type -> gameplay.v1.ListUserServersResponse
	32, // 32: gameplay.v1.ServerService.GetUserServerPermissions:output_type -> gameplay.v1.GetUserServerPermissionsResponse
	33, // 33: gameplay.v1.ServerService.UpdateServer:output_type -> gameplay.v1.UpdateServerResponse
	34, // 34: gameplay.v1.ServerService.ArchiveServer:output_type -> gameplay.v1.ArchiveServerResponse
	35, // 35: gameplay.v1.ServerService.GetServerTreasury:output_type -> gameplay.v1.GetServerTreasuryResponse
	36, // 36: gameplay.v1.ServerAdminService.AddServerAdmin:output_type -> gameplay.v1.AddServerAdminResponse
	37, // 37: gameplay.v1.ServerAdminService.ListServerAdmins:output_type -> gameplay.v1.ListServerAdminsResponse
	38, // 38: gameplay.v1.ServerAdminService.RemoveServerAdmin:output_type -> gameplay.v1.RemoveServerAdminResponse
	39, // 39: gameplay.v1.WordService.AddWords:output_type -> gameplay.v1.AddWordsResponse
	40, // 40: gameplay.v1.WordService.GetRandomWords:output_type -> gameplay.v1.GetRandomWordsResponse
	41, // 41: gameplay.v1.WordService.ListWords:output_type -> gameplay.v1.ListWordsResponse
	42, // 42: gameplay.v1.WordService.RemoveWords:output_type -> gameplay.v1.RemoveWordsResponse
	43, // 43: gameplay.v1.WordService.RemoveAllWords:output_type -> gameplay.v1.RemoveAllWordsResponse
	44, // 44: gameplay.v1.GameService.GetCurrentGame:output_type -> gameplay.v1.GetCurrentGameResponse
	45, // 45: gameplay.v1.GameService.GetGame:output_type -> gameplay.v1.GetGameResponse
	46, // 46: gameplay.v1.GameService.GetGameLeaderboard:output_type -> gameplay.v1.GetGameLeaderboardResponse
	47, // 47: gameplay.v1.GameService.ListServerGames:output_type -> gameplay.v1.ListServerGamesResponse
	48, // 48: gameplay.v1.GameService.GetServerLeaderboard:output_type -> gameplay.v1.GetServerLeaderboardResponse
	49, // 49: gameplay.v1.GameService.ListUserGames:output_type -> gameplay.v1.ListUserGamesResponse
	50, // 50: gameplay.v1.GameService.GetGlobalLeaderboard:output_type -> gameplay.v1.GetGlobalLeaderboardResponse
	51, // 51: gameplay.v1.GameService.GetUserStats:output_type -> gameplay.v1.GetUserStatsResponse
	52, // 52: gameplay.v1.GameService.JoinGame:output_type -> gameplay.v1.JoinGameResponse
	53, // 53: gameplay.v1.GameService.ReplayGame:output_type -> gameplay.v1.ReplayGameResponse
	27, // [27:54] is the sub-list for method output_type
	0,  // [0:27] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gameplay_v1_service_gameplay_proto_init() }
func file_gameplay_v1_service_gameplay_proto_init() {
	if File_gameplay_v1_service_gameplay_proto != nil {
		return
	}
	file_gameplay_v1_rpc_server_service_proto_init()
	file_gameplay_v1_rpc_server_admin_service_proto_init()
	file_gameplay_v1_rpc_word_service_proto_init()
	file_gameplay_v1_rpc_game_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gameplay_v1_service_gameplay_proto_rawDesc), len(file_gameplay_v1_service_gameplay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_gameplay_v1_service_gameplay_proto_goTypes,
		DependencyIndexes: file_gameplay_v1_service_gameplay_proto_depIdxs,
	}.Build()
	File_gameplay_v1_service_gameplay_proto = out.File
	file_gameplay_v1_service_gameplay_proto_goTypes = nil
	file_gameplay_v1_service_gameplay_proto_depIdxs = nil
}
