// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: gameplay/v1/service_gameplay.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gameplay_v1_service_gameplay_proto protoreflect.FileDescriptor

const file_gameplay_v1_service_gameplay_proto_rawDesc = "" +
	"\n" +
	"\"gameplay/v1/service_gameplay.proto\x12\vgameplay.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a$gameplay/v1/rpc_server_service.proto2\xae\x01\n" +
	"\rServerService\x12\x9c\x01\n" +
	"\fCreateServer\x12 .gameplay.v1.CreateServerRequest\x1a!.gameplay.v1.CreateServerResponse\"G\x92A2\x12\rCreate server\x1a\x13Create a new serverb\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\f:\x01*\"\a/serverB\xcf\x02\x92A\x9f\x01\x124\n" +
	"\x10Gameplay Service\"\x1d\n" +
	"\aSpazzle\x12\x12https://spazzle.io2\x010ZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\n" +
	"\x0fcom.gameplay.v1B\x14ServiceGameplayProtoP\x01Z6github.com/spazzle-io/spazzle-api/services/gameplay/pb\xa2\x02\x03GXX\xaa\x02\vGameplay.V1\xca\x02\vGameplay\\V1\xe2\x02\x17Gameplay\\V1\\GPBMetadata\xea\x02\fGameplay::V1b\x06proto3"

var file_gameplay_v1_service_gameplay_proto_goTypes = []any{
	(*CreateServerRequest)(nil),  // 0: gameplay.v1.CreateServerRequest
	(*CreateServerResponse)(nil), // 1: gameplay.v1.CreateServerResponse
}
var file_gameplay_v1_service_gameplay_proto_depIdxs = []int32{
	0, // 0: gameplay.v1.ServerService.CreateServer:input_type -> gameplay.v1.CreateServerRequest
	1, // 1: gameplay.v1.ServerService.CreateServer:output_type -> gameplay.v1.CreateServerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gameplay_v1_service_gameplay_proto_init() }
func file_gameplay_v1_service_gameplay_proto_init() {
	if File_gameplay_v1_service_gameplay_proto != nil {
		return
	}
	file_gameplay_v1_rpc_server_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gameplay_v1_service_gameplay_proto_rawDesc), len(file_gameplay_v1_service_gameplay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gameplay_v1_service_gameplay_proto_goTypes,
		DependencyIndexes: file_gameplay_v1_service_gameplay_proto_depIdxs,
	}.Build()
	File_gameplay_v1_service_gameplay_proto = out.File
	file_gameplay_v1_service_gameplay_proto_goTypes = nil
	file_gameplay_v1_service_gameplay_proto_depIdxs = nil
}
