version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: main
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: main
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gomod"
    directories:
      - "services/*"
    schedule:
      interval: "weekly"
    target-branch: main
    groups:
      go-dependency-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      go-dependency-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    commit-message:
      prefix: "chore"
      include: "scope"
