coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 50%
        base: auto
    patch:
      default:
        target: 0%
        threshold: 50%
        base: auto
ignore:
  - "**/docs/**/*"
  - "services/proto"
  - "libs/common/docs"
