version: "2"
formatters:
  enable:
    - gofumpt
    - goimports
linters:
  enable:
    - goconst
    - gocritic
    - gosec
    - misspell
  exclusions:
    rules:
      - linters:
          - goconst
        path: _test\.go
