// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: users/v1/rpc_create_user.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	GamerTag      string                 `protobuf:"bytes,2,opt,name=gamer_tag,json=gamerTag,proto3" json:"gamer_tag,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_users_v1_rpc_create_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_rpc_create_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_rpc_create_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *CreateUserRequest) GetGamerTag() string {
	if x != nil {
		return x.GamerTag
	}
	return ""
}

func (x *CreateUserRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Session       *Session               `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_users_v1_rpc_create_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_rpc_create_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_rpc_create_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_users_v1_rpc_create_user_proto protoreflect.FileDescriptor

const file_users_v1_rpc_create_user_proto_rawDesc = "" +
	"\n" +
	"\x1eusers/v1/rpc_create_user.proto\x12\busers.v1\x1a\x1bbuf/validate/validate.proto\x1a\x15users/v1/common.proto\"\x85\x01\n" +
	"\x11CreateUserRequest\x12-\n" +
	"\x0ewallet_address\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\rwalletAddress\x12\x1b\n" +
	"\tgamer_tag\x18\x02 \x01(\tR\bgamerTag\x12$\n" +
	"\tsignature\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tsignature\"e\n" +
	"\x12CreateUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.users.v1.UserR\x04user\x12+\n" +
	"\asession\x18\x02 \x01(\v2\x11.users.v1.SessionR\asessionB\x98\x01\n" +
	"\fcom.users.v1B\x12RpcCreateUserProtoP\x01Z3github.com/spazzle-io/spazzle-api/services/users/pb\xa2\x02\x03UXX\xaa\x02\bUsers.V1\xca\x02\bUsers\\V1\xe2\x02\x14Users\\V1\\GPBMetadata\xea\x02\tUsers::V1b\x06proto3"

var (
	file_users_v1_rpc_create_user_proto_rawDescOnce sync.Once
	file_users_v1_rpc_create_user_proto_rawDescData []byte
)

func file_users_v1_rpc_create_user_proto_rawDescGZIP() []byte {
	file_users_v1_rpc_create_user_proto_rawDescOnce.Do(func() {
		file_users_v1_rpc_create_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_v1_rpc_create_user_proto_rawDesc), len(file_users_v1_rpc_create_user_proto_rawDesc)))
	})
	return file_users_v1_rpc_create_user_proto_rawDescData
}

var file_users_v1_rpc_create_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_users_v1_rpc_create_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: users.v1.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: users.v1.CreateUserResponse
	(*User)(nil),               // 2: users.v1.User
	(*Session)(nil),            // 3: users.v1.Session
}
var file_users_v1_rpc_create_user_proto_depIdxs = []int32{
	2, // 0: users.v1.CreateUserResponse.user:type_name -> users.v1.User
	3, // 1: users.v1.CreateUserResponse.session:type_name -> users.v1.Session
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_users_v1_rpc_create_user_proto_init() }
func file_users_v1_rpc_create_user_proto_init() {
	if File_users_v1_rpc_create_user_proto != nil {
		return
	}
	file_users_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_rpc_create_user_proto_rawDesc), len(file_users_v1_rpc_create_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_v1_rpc_create_user_proto_goTypes,
		DependencyIndexes: file_users_v1_rpc_create_user_proto_depIdxs,
		MessageInfos:      file_users_v1_rpc_create_user_proto_msgTypes,
	}.Build()
	File_users_v1_rpc_create_user_proto = out.File
	file_users_v1_rpc_create_user_proto_goTypes = nil
	file_users_v1_rpc_create_user_proto_depIdxs = nil
}
