// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: users/v1/rpc_get_user_by_wallet_address.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByWalletAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByWalletAddressRequest) Reset() {
	*x = GetUserByWalletAddressRequest{}
	mi := &file_users_v1_rpc_get_user_by_wallet_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByWalletAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByWalletAddressRequest) ProtoMessage() {}

func (x *GetUserByWalletAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_rpc_get_user_by_wallet_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByWalletAddressRequest.ProtoReflect.Descriptor instead.
func (*GetUserByWalletAddressRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_rpc_get_user_by_wallet_address_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByWalletAddressRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type GetUserByWalletAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByWalletAddressResponse) Reset() {
	*x = GetUserByWalletAddressResponse{}
	mi := &file_users_v1_rpc_get_user_by_wallet_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByWalletAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByWalletAddressResponse) ProtoMessage() {}

func (x *GetUserByWalletAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_rpc_get_user_by_wallet_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByWalletAddressResponse.ProtoReflect.Descriptor instead.
func (*GetUserByWalletAddressResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_rpc_get_user_by_wallet_address_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByWalletAddressResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_users_v1_rpc_get_user_by_wallet_address_proto protoreflect.FileDescriptor

const file_users_v1_rpc_get_user_by_wallet_address_proto_rawDesc = "" +
	"\n" +
	"-users/v1/rpc_get_user_by_wallet_address.proto\x12\busers.v1\x1a\x1bbuf/validate/validate.proto\x1a\x15users/v1/common.proto\"N\n" +
	"\x1dGetUserByWalletAddressRequest\x12-\n" +
	"\x0ewallet_address\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\rwalletAddress\"D\n" +
	"\x1eGetUserByWalletAddressResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.users.v1.UserR\x04userB\xa4\x01\n" +
	"\fcom.users.v1B\x1eRpcGetUserByWalletAddressProtoP\x01Z3github.com/spazzle-io/spazzle-api/services/users/pb\xa2\x02\x03UXX\xaa\x02\bUsers.V1\xca\x02\bUsers\\V1\xe2\x02\x14Users\\V1\\GPBMetadata\xea\x02\tUsers::V1b\x06proto3"

var (
	file_users_v1_rpc_get_user_by_wallet_address_proto_rawDescOnce sync.Once
	file_users_v1_rpc_get_user_by_wallet_address_proto_rawDescData []byte
)

func file_users_v1_rpc_get_user_by_wallet_address_proto_rawDescGZIP() []byte {
	file_users_v1_rpc_get_user_by_wallet_address_proto_rawDescOnce.Do(func() {
		file_users_v1_rpc_get_user_by_wallet_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_v1_rpc_get_user_by_wallet_address_proto_rawDesc), len(file_users_v1_rpc_get_user_by_wallet_address_proto_rawDesc)))
	})
	return file_users_v1_rpc_get_user_by_wallet_address_proto_rawDescData
}

var file_users_v1_rpc_get_user_by_wallet_address_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_users_v1_rpc_get_user_by_wallet_address_proto_goTypes = []any{
	(*GetUserByWalletAddressRequest)(nil),  // 0: users.v1.GetUserByWalletAddressRequest
	(*GetUserByWalletAddressResponse)(nil), // 1: users.v1.GetUserByWalletAddressResponse
	(*User)(nil),                           // 2: users.v1.User
}
var file_users_v1_rpc_get_user_by_wallet_address_proto_depIdxs = []int32{
	2, // 0: users.v1.GetUserByWalletAddressResponse.user:type_name -> users.v1.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_users_v1_rpc_get_user_by_wallet_address_proto_init() }
func file_users_v1_rpc_get_user_by_wallet_address_proto_init() {
	if File_users_v1_rpc_get_user_by_wallet_address_proto != nil {
		return
	}
	file_users_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_rpc_get_user_by_wallet_address_proto_rawDesc), len(file_users_v1_rpc_get_user_by_wallet_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_v1_rpc_get_user_by_wallet_address_proto_goTypes,
		DependencyIndexes: file_users_v1_rpc_get_user_by_wallet_address_proto_depIdxs,
		MessageInfos:      file_users_v1_rpc_get_user_by_wallet_address_proto_msgTypes,
	}.Build()
	File_users_v1_rpc_get_user_by_wallet_address_proto = out.File
	file_users_v1_rpc_get_user_by_wallet_address_proto_goTypes = nil
	file_users_v1_rpc_get_user_by_wallet_address_proto_depIdxs = nil
}
