// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: users/v1/rpc_list_users.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_users_v1_rpc_list_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_rpc_list_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_rpc_list_users_proto_rawDescGZIP(), []int{0}
}

func (x *ListUsersRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	NumTotalUsers uint32                 `protobuf:"varint,3,opt,name=num_total_users,json=numTotalUsers,proto3" json:"num_total_users,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_users_v1_rpc_list_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_rpc_list_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_rpc_list_users_proto_rawDescGZIP(), []int{1}
}

func (x *ListUsersResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResponse) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersResponse) GetNumTotalUsers() uint32 {
	if x != nil {
		return x.NumTotalUsers
	}
	return 0
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_users_v1_rpc_list_users_proto protoreflect.FileDescriptor

const file_users_v1_rpc_list_users_proto_rawDesc = "" +
	"\n" +
	"\x1dusers/v1/rpc_list_users.proto\x12\busers.v1\x1a\x15users/v1/common.proto\"C\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"\x92\x01\n" +
	"\x11ListUsersResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12&\n" +
	"\x0fnum_total_users\x18\x03 \x01(\rR\rnumTotalUsers\x12$\n" +
	"\x05users\x18\x04 \x03(\v2\x0e.users.v1.UserR\x05usersB\x97\x01\n" +
	"\fcom.users.v1B\x11RpcListUsersProtoP\x01Z3github.com/spazzle-io/spazzle-api/services/users/pb\xa2\x02\x03UXX\xaa\x02\bUsers.V1\xca\x02\bUsers\\V1\xe2\x02\x14Users\\V1\\GPBMetadata\xea\x02\tUsers::V1b\x06proto3"

var (
	file_users_v1_rpc_list_users_proto_rawDescOnce sync.Once
	file_users_v1_rpc_list_users_proto_rawDescData []byte
)

func file_users_v1_rpc_list_users_proto_rawDescGZIP() []byte {
	file_users_v1_rpc_list_users_proto_rawDescOnce.Do(func() {
		file_users_v1_rpc_list_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_v1_rpc_list_users_proto_rawDesc), len(file_users_v1_rpc_list_users_proto_rawDesc)))
	})
	return file_users_v1_rpc_list_users_proto_rawDescData
}

var file_users_v1_rpc_list_users_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_users_v1_rpc_list_users_proto_goTypes = []any{
	(*ListUsersRequest)(nil),  // 0: users.v1.ListUsersRequest
	(*ListUsersResponse)(nil), // 1: users.v1.ListUsersResponse
	(*User)(nil),              // 2: users.v1.User
}
var file_users_v1_rpc_list_users_proto_depIdxs = []int32{
	2, // 0: users.v1.ListUsersResponse.users:type_name -> users.v1.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_users_v1_rpc_list_users_proto_init() }
func file_users_v1_rpc_list_users_proto_init() {
	if File_users_v1_rpc_list_users_proto != nil {
		return
	}
	file_users_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_rpc_list_users_proto_rawDesc), len(file_users_v1_rpc_list_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_v1_rpc_list_users_proto_goTypes,
		DependencyIndexes: file_users_v1_rpc_list_users_proto_depIdxs,
		MessageInfos:      file_users_v1_rpc_list_users_proto_msgTypes,
	}.Build()
	File_users_v1_rpc_list_users_proto = out.File
	file_users_v1_rpc_list_users_proto_goTypes = nil
	file_users_v1_rpc_list_users_proto_depIdxs = nil
}
