syntax = "proto3";

package users.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "users/v1/common.proto";

option go_package = "github.com/spazzle-io/spazzle-api/services/users/pb";

message AuthenticateUserRequest {
  string wallet_address = 1 [(buf.validate.field).required = true];
  string signature = 2 [(buf.validate.field).required = true];
}

message AuthenticateUserResponse {
  User user = 1;
  Session session = 2;
}

message Session {
  string session_id = 1;
  string access_token = 2;
  string refresh_token = 3;
  google.protobuf.Timestamp access_token_expires_at = 4;
  google.protobuf.Timestamp refresh_token_expires_at = 5;
  string token_type = 6;
}
