syntax = "proto3";

package users.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "users/v1/rpc_authenticate_user.proto";
import "users/v1/rpc_get_user.proto";
import "users/v1/rpc_get_user_by_wallet_address.proto";

option go_package = "github.com/spazzle-io/spazzle-api/services/users/pb";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Users Service";
    version: "0";
    contact: {
      name: "Spazzle";
      url: "https://spazzle.io";
    };
  };
  security_definitions: {
    security: {
      key: "bearer"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "Authorization"
        description: "Authentication token, prefixed by Bearer: bearer <token>"
      }
    }
  };
  security: {
    security_requirement: {
      key: "bearer"
    }
  };
};

service UsersService {
  rpc GetUser(GetUserRequest) returns (GetUserResponse) {
    option (google.api.http) = {
      get: "/users/{id}"
    };

    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "Get user";
      description: "Get user by id";
      security: {};
    };
  }

  rpc GetUserByWalletAddress(GetUserByWalletAddressRequest) returns (GetUserByWalletAddressResponse) {
    option (google.api.http) = {
      get: "/users/by-wallet-address/{wallet_address}"
    };

    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "Get user by wallet address";
      description: "Get user by Ethereum wallet address";
      security: {};
    };
  }

  rpc AuthenticateUser(AuthenticateUserRequest) returns (AuthenticateUserResponse) {
    option (google.api.http) = {
      post: "/users/authenticate",
      body: "*"
    };

    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "Authenticate user";
      description: "Authenticate a new or existing user by verifying their Ethereum wallet address using a cryptographic signature";
      security: {};
    };
  }
}
