// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    wallet_address
) VALUES (
    $1
) RETURNING id, wallet_address, gamer_tag, created_at
`

func (q *Queries) CreateUser(ctx context.Context, walletAddress string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, walletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.GamerTag,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalUserCount = `-- name: GetTotalUserCount :one
SELECT COUNT(*) as total_users FROM users
`

func (q *Queries) GetTotalUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalUserCount)
	var total_users int64
	err := row.Scan(&total_users)
	return total_users, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    id, wallet_address, gamer_tag, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.GamerTag,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByWalletAddress = `-- name: GetUserByWalletAddress :one
SELECT
    id, wallet_address, gamer_tag, created_at
FROM users
WHERE wallet_address = $1
    LIMIT 1
`

func (q *Queries) GetUserByWalletAddress(ctx context.Context, walletAddress string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWalletAddress, walletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.GamerTag,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id, wallet_address, gamer_tag, created_at
FROM USERS
WHERE (
    $1::timestamptz IS NULL
    OR created_at < $1
    OR (created_at = $1 AND id < $2)
) ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListUsersParams struct {
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.AfterCreatedAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.WalletAddress,
			&i.GamerTag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    gamer_tag = COALESCE($1, gamer_tag)
WHERE
    id = $2
RETURNING id, wallet_address, gamer_tag, created_at
`

type UpdateUserParams struct {
	GamerTag pgtype.Text `json:"gamer_tag"`
	UserID   uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.GamerTag, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.GamerTag,
		&i.CreatedAt,
	)
	return i, err
}
