// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	AddServerAdmin(ctx context.Context, arg AddServerAdminParams) (ServerAdmin, error)
	AddWordsToServer(ctx context.Context, arg AddWordsToServerParams) (pgconn.CommandTag, error)
	CreateServer(ctx context.Context, arg CreateServerParams) (Server, error)
	GetRandomWordsForServer(ctx context.Context, arg GetRandomWordsForServerParams) ([]string, error)
	GetServerById(ctx context.Context, serverID uuid.UUID) (Server, error)
	GetServerByName(ctx context.Context, name string) (Server, error)
	GetServerUserPermissions(ctx context.Context, arg GetServerUserPermissionsParams) (GetServerUserPermissionsRow, error)
	GetTotalServerCount(ctx context.Context) (int64, error)
	GetTotalUserServersCount(ctx context.Context, userID uuid.UUID) (int64, error)
	ListServerAdmins(ctx context.Context, arg ListServerAdminsParams) ([]ServerAdmin, error)
	ListServers(ctx context.Context, arg ListServersParams) ([]Server, error)
	ListUserServers(ctx context.Context, arg ListUserServersParams) ([]ListUserServersRow, error)
	ListWords(ctx context.Context, arg ListWordsParams) ([]ListWordsRow, error)
	RemoveAllWordsFromServer(ctx context.Context, serverID uuid.UUID) (pgconn.CommandTag, error)
	RemoveServerAdmin(ctx context.Context, arg RemoveServerAdminParams) error
	RemoveWordsFromServer(ctx context.Context, arg RemoveWordsFromServerParams) (pgconn.CommandTag, error)
	UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error)
}

var _ Querier = (*Queries)(nil)
