// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: server_admins.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addServerAdmin = `-- name: AddServerAdmin :one
INSERT INTO server_admins (
    server_id,
    user_id
) VALUES (
    $1, $2
) RETURNING server_id, user_id, added_at
`

type AddServerAdminParams struct {
	ServerID uuid.UUID `json:"server_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) AddServerAdmin(ctx context.Context, arg AddServerAdminParams) (ServerAdmin, error) {
	row := q.db.QueryRow(ctx, addServerAdmin, arg.ServerID, arg.UserID)
	var i ServerAdmin
	err := row.Scan(&i.ServerID, &i.UserID, &i.AddedAt)
	return i, err
}

const listServerAdmins = `-- name: ListServerAdmins :many
SELECT
    server_id,
    user_id,
    added_at
FROM server_admins
WHERE server_id = $1
AND (
    $2::timestamptz IS NULL
    OR added_at < $2
    OR (added_at = $2 AND user_id < $3)
) ORDER BY added_at DESC, user_id DESC
LIMIT $4
`

type ListServerAdminsParams struct {
	ServerID     uuid.UUID          `json:"server_id"`
	AfterAddedAt pgtype.Timestamptz `json:"after_added_at"`
	AfterUserID  pgtype.UUID        `json:"after_user_id"`
	PageSize     int32              `json:"page_size"`
}

func (q *Queries) ListServerAdmins(ctx context.Context, arg ListServerAdminsParams) ([]ServerAdmin, error) {
	rows, err := q.db.Query(ctx, listServerAdmins,
		arg.ServerID,
		arg.AfterAddedAt,
		arg.AfterUserID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServerAdmin{}
	for rows.Next() {
		var i ServerAdmin
		if err := rows.Scan(&i.ServerID, &i.UserID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeServerAdmin = `-- name: RemoveServerAdmin :exec
DELETE FROM server_admins
WHERE server_id = $1 AND user_id = $2
`

type RemoveServerAdminParams struct {
	ServerID uuid.UUID `json:"server_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveServerAdmin(ctx context.Context, arg RemoveServerAdminParams) error {
	_, err := q.db.Exec(ctx, removeServerAdmin, arg.ServerID, arg.UserID)
	return err
}
