// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: server_player_stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getServerLeaderboard = `-- name: GetServerLeaderboard :many
SELECT
    server_id,
    user_id,
    total_games,
    total_score,
    total_pnl,
    total_volume,
    updated_at
FROM server_player_stats
WHERE server_id = $1
AND (
    $2::numeric IS NULL
    OR total_pnl < $2
    OR (total_pnl = $2 AND user_id < $3)
)
ORDER BY total_pnl DESC, user_id DESC
LIMIT $4
`

type GetServerLeaderboardParams struct {
	ServerID      uuid.UUID      `json:"server_id"`
	AfterTotalPnl pgtype.Numeric `json:"after_total_pnl"`
	AfterID       pgtype.UUID    `json:"after_id"`
	PageSize      int32          `json:"page_size"`
}

func (q *Queries) GetServerLeaderboard(ctx context.Context, arg GetServerLeaderboardParams) ([]ServerPlayerStat, error) {
	rows, err := q.db.Query(ctx, getServerLeaderboard,
		arg.ServerID,
		arg.AfterTotalPnl,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServerPlayerStat{}
	for rows.Next() {
		var i ServerPlayerStat
		if err := rows.Scan(
			&i.ServerID,
			&i.UserID,
			&i.TotalGames,
			&i.TotalScore,
			&i.TotalPnl,
			&i.TotalVolume,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalServerPlayerStatsCount = `-- name: GetTotalServerPlayerStatsCount :one
SELECT COUNT(*)
FROM server_player_stats
WHERE server_id = $1
`

func (q *Queries) GetTotalServerPlayerStatsCount(ctx context.Context, serverID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalServerPlayerStatsCount, serverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertServerPlayerStats = `-- name: UpsertServerPlayerStats :exec
INSERT INTO server_player_stats (
    server_id,
    user_id,
    total_games,
    total_score,
    total_pnl,
    total_volume
) VALUES (
   $1,
   $2,
   1,
   $3,
   $4,
   $5
) ON CONFLICT (server_id, user_id) DO UPDATE
SET
    total_games = server_player_stats.total_games + 1,
    total_score = server_player_stats.total_score + $3,
    total_pnl = server_player_stats.total_pnl + $4,
    total_volume = server_player_stats.total_volume + $5,
    updated_at = now()
`

type UpsertServerPlayerStatsParams struct {
	ServerID uuid.UUID      `json:"server_id"`
	UserID   uuid.UUID      `json:"user_id"`
	Score    int32          `json:"score"`
	Pnl      pgtype.Numeric `json:"pnl"`
	Volume   pgtype.Numeric `json:"volume"`
}

func (q *Queries) UpsertServerPlayerStats(ctx context.Context, arg UpsertServerPlayerStatsParams) error {
	_, err := q.db.Exec(ctx, upsertServerPlayerStats,
		arg.ServerID,
		arg.UserID,
		arg.Score,
		arg.Pnl,
		arg.Volume,
	)
	return err
}
