// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: servers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (
    name,
    owner_id,
    server_address,
    stake_per_game,
    num_rounds_per_game,
    round_duration_secs,
    num_drawing_options
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, owner_id, num_admins, num_custom_words, server_address, stake_per_game, num_rounds_per_game, round_duration_secs, num_drawing_options, is_archived, archived_at, created_at
`

type CreateServerParams struct {
	Name              string         `json:"name"`
	OwnerID           uuid.UUID      `json:"owner_id"`
	ServerAddress     string         `json:"server_address"`
	StakePerGame      pgtype.Numeric `json:"stake_per_game"`
	NumRoundsPerGame  int32          `json:"num_rounds_per_game"`
	RoundDurationSecs int32          `json:"round_duration_secs"`
	NumDrawingOptions int32          `json:"num_drawing_options"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.Name,
		arg.OwnerID,
		arg.ServerAddress,
		arg.StakePerGame,
		arg.NumRoundsPerGame,
		arg.RoundDurationSecs,
		arg.NumDrawingOptions,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NumAdmins,
		&i.NumCustomWords,
		&i.ServerAddress,
		&i.StakePerGame,
		&i.NumRoundsPerGame,
		&i.RoundDurationSecs,
		&i.NumDrawingOptions,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getServerById = `-- name: GetServerById :one
SELECT
    id,
    name,
    owner_id,
    num_admins,
    num_custom_words,
    server_address,
    stake_per_game,
    num_rounds_per_game,
    round_duration_secs,
    num_drawing_options,
    is_archived,
    archived_at,
    created_at
FROM servers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetServerById(ctx context.Context, serverID uuid.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServerById, serverID)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NumAdmins,
		&i.NumCustomWords,
		&i.ServerAddress,
		&i.StakePerGame,
		&i.NumRoundsPerGame,
		&i.RoundDurationSecs,
		&i.NumDrawingOptions,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getServerByName = `-- name: GetServerByName :one
SELECT
    id,
    name,
    owner_id,
    num_admins,
    num_custom_words,
    server_address,
    stake_per_game,
    num_rounds_per_game,
    round_duration_secs,
    num_drawing_options,
    is_archived,
    archived_at,
    created_at
FROM servers
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetServerByName(ctx context.Context, name string) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByName, name)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NumAdmins,
		&i.NumCustomWords,
		&i.ServerAddress,
		&i.StakePerGame,
		&i.NumRoundsPerGame,
		&i.RoundDurationSecs,
		&i.NumDrawingOptions,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getServerUserPermissions = `-- name: GetServerUserPermissions :one
SELECT
    s.owner_id = $1 AS is_owner,
    (sa.user_id IS NOT NULL)::bool AS is_admin,
    (s.owner_id = $1 OR (sa.user_id IS NOT NULL)::bool)::bool AS has_elevated_permissions
FROM servers s
    LEFT JOIN server_admins sa
    ON sa.server_id = s.id AND sa.user_id = $1
WHERE s.id = $2
`

type GetServerUserPermissionsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ServerID uuid.UUID `json:"server_id"`
}

type GetServerUserPermissionsRow struct {
	IsOwner                bool `json:"is_owner"`
	IsAdmin                bool `json:"is_admin"`
	HasElevatedPermissions bool `json:"has_elevated_permissions"`
}

func (q *Queries) GetServerUserPermissions(ctx context.Context, arg GetServerUserPermissionsParams) (GetServerUserPermissionsRow, error) {
	row := q.db.QueryRow(ctx, getServerUserPermissions, arg.UserID, arg.ServerID)
	var i GetServerUserPermissionsRow
	err := row.Scan(&i.IsOwner, &i.IsAdmin, &i.HasElevatedPermissions)
	return i, err
}

const getTotalServerCount = `-- name: GetTotalServerCount :one
SELECT COUNT(*) FROM servers
`

func (q *Queries) GetTotalServerCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalServerCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalUserServersCount = `-- name: GetTotalUserServersCount :one
SELECT COUNT(*)
FROM servers s
WHERE
    s.owner_id = $1
    OR EXISTS (
        SELECT 1
        FROM server_admins sa
        WHERE sa.server_id = s.id AND sa.user_id = $1
        LIMIT 1
    )
`

func (q *Queries) GetTotalUserServersCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalUserServersCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listServers = `-- name: ListServers :many
SELECT
    id,
    name,
    owner_id,
    num_admins,
    num_custom_words,
    server_address,
    stake_per_game,
    num_rounds_per_game,
    round_duration_secs,
    num_drawing_options,
    is_archived,
    archived_at,
    created_at
FROM servers
WHERE (
    $1::timestamptz IS NULL
    OR created_at < $1
    OR (created_at = $1 AND id < $2)
) ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListServersParams struct {
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListServers(ctx context.Context, arg ListServersParams) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServers, arg.AfterCreatedAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NumAdmins,
			&i.NumCustomWords,
			&i.ServerAddress,
			&i.StakePerGame,
			&i.NumRoundsPerGame,
			&i.RoundDurationSecs,
			&i.NumDrawingOptions,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserServers = `-- name: ListUserServers :many
SELECT
    s.id,
    s.name,
    s.owner_id,
    s.num_admins,
    s.num_custom_words,
    s.server_address,
    s.stake_per_game,
    s.num_rounds_per_game,
    s.round_duration_secs,
    s.num_drawing_options,
    s.is_archived,
    s.archived_at,
    s.created_at,
    (s.owner_id = $1) AS is_owner,
    (sa.user_id IS NOT NULL)::bool AS is_admin
FROM servers s
    LEFT JOIN LATERAL (
        SELECT sa.user_id
        FROM server_admins sa
        WHERE sa.server_id = s.id AND sa.user_id = $1
        LIMIT 1
    ) sa ON TRUE
WHERE (s.owner_id = $1 OR sa.user_id = $1)
AND (
    $2::timestamptz IS NULL
    OR s.created_at < $2
    OR (s.created_at = $2 AND s.id < $3)
) ORDER BY s.created_at DESC, s.id DESC
LIMIT $4
`

type ListUserServersParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

type ListUserServersRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	OwnerID           uuid.UUID          `json:"owner_id"`
	NumAdmins         int32              `json:"num_admins"`
	NumCustomWords    int32              `json:"num_custom_words"`
	ServerAddress     string             `json:"server_address"`
	StakePerGame      pgtype.Numeric     `json:"stake_per_game"`
	NumRoundsPerGame  int32              `json:"num_rounds_per_game"`
	RoundDurationSecs int32              `json:"round_duration_secs"`
	NumDrawingOptions int32              `json:"num_drawing_options"`
	IsArchived        bool               `json:"is_archived"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	CreatedAt         time.Time          `json:"created_at"`
	IsOwner           bool               `json:"is_owner"`
	IsAdmin           bool               `json:"is_admin"`
}

func (q *Queries) ListUserServers(ctx context.Context, arg ListUserServersParams) ([]ListUserServersRow, error) {
	rows, err := q.db.Query(ctx, listUserServers,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserServersRow{}
	for rows.Next() {
		var i ListUserServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.NumAdmins,
			&i.NumCustomWords,
			&i.ServerAddress,
			&i.StakePerGame,
			&i.NumRoundsPerGame,
			&i.RoundDurationSecs,
			&i.NumDrawingOptions,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.IsOwner,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServer = `-- name: UpdateServer :one
UPDATE servers
SET
    name = COALESCE($1, name),
    owner_id = COALESCE($2, owner_id),
    num_admins = COALESCE($3, num_admins),
    num_custom_words = COALESCE($4, num_custom_words),
    server_address = COALESCE($5, server_address),
    stake_per_game = COALESCE($6, stake_per_game),
    num_rounds_per_game = COALESCE($7, num_rounds_per_game),
    round_duration_secs = COALESCE($8, round_duration_secs),
    num_drawing_options = COALESCE($9, num_drawing_options),
    is_archived = COALESCE($10, is_archived),
    archived_at = COALESCE($11, archived_at)
WHERE
    id = $12
    RETURNING id, name, owner_id, num_admins, num_custom_words, server_address, stake_per_game, num_rounds_per_game, round_duration_secs, num_drawing_options, is_archived, archived_at, created_at
`

type UpdateServerParams struct {
	Name              pgtype.Text        `json:"name"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	NumAdmins         pgtype.Int4        `json:"num_admins"`
	NumCustomWords    pgtype.Int4        `json:"num_custom_words"`
	ServerAddress     pgtype.Text        `json:"server_address"`
	StakePerGame      pgtype.Numeric     `json:"stake_per_game"`
	NumRoundsPerGame  pgtype.Int4        `json:"num_rounds_per_game"`
	RoundDurationSecs pgtype.Int4        `json:"round_duration_secs"`
	NumDrawingOptions pgtype.Int4        `json:"num_drawing_options"`
	IsArchived        pgtype.Bool        `json:"is_archived"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	ServerID          uuid.UUID          `json:"server_id"`
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServer,
		arg.Name,
		arg.OwnerID,
		arg.NumAdmins,
		arg.NumCustomWords,
		arg.ServerAddress,
		arg.StakePerGame,
		arg.NumRoundsPerGame,
		arg.RoundDurationSecs,
		arg.NumDrawingOptions,
		arg.IsArchived,
		arg.ArchivedAt,
		arg.ServerID,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.NumAdmins,
		&i.NumCustomWords,
		&i.ServerAddress,
		&i.StakePerGame,
		&i.NumRoundsPerGame,
		&i.RoundDurationSecs,
		&i.NumDrawingOptions,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
