// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: words.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const addWordsToServer = `-- name: AddWordsToServer :execresult
WITH next_index AS (
    SELECT COALESCE(MAX(word_idx), 0) + 1 AS start_index
    FROM words
    WHERE server_id = $1::uuid
)
INSERT INTO words (server_id, word, word_idx)
SELECT
    $1::uuid,
    w.word,
    next_index.start_index + ROW_NUMBER() OVER () - 1
FROM next_index
JOIN (
    SELECT unnest($2::text[]) AS word
) AS w ON true
ON CONFLICT (server_id, word) DO NOTHING
`

type AddWordsToServerParams struct {
	ServerID uuid.UUID `json:"server_id"`
	Words    []string  `json:"words"`
}

func (q *Queries) AddWordsToServer(ctx context.Context, arg AddWordsToServerParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, addWordsToServer, arg.ServerID, arg.Words)
}

const getRandomWordsForServer = `-- name: GetRandomWordsForServer :many
WITH bounds AS (
    SELECT MIN(word_idx) AS min_idx, MAX(word_idx) AS max_idx
    FROM words
    WHERE server_id = $1::uuid
),
random_indices AS (
    SELECT FLOOR(random() * (bounds.max_idx - bounds.min_idx + 1) + bounds.min_idx)::int AS idx
    FROM bounds, generate_series(1, $2::int * COALESCE($3::int, 10))
),
selected AS (
    SELECT id, server_id, word, added_at FROM (
        SELECT DISTINCT w.id, w.server_id, w.word, w.added_at
        FROM words w
        JOIN random_indices r ON w.word_idx = r.idx
        WHERE w.server_id = $1
    ) AS sub
    ORDER BY RANDOM()
    LIMIT $2
),
fallback AS (
    SELECT w.id, w.server_id, w.word, w.added_at
    FROM words w
    WHERE w.server_id = $1
    AND NOT EXISTS (
        SELECT 1 FROM selected s WHERE s.id = w.id
    )
    ORDER BY RANDOM()
    LIMIT GREATEST($2 - (SELECT COUNT(*) FROM selected), 0)
),
combined AS (
    SELECT id, server_id, word, added_at FROM selected
    UNION ALL
    SELECT id, server_id, word, added_at FROM fallback
)
SELECT id, server_id, word, added_at FROM combined
ORDER BY RANDOM()
`

type GetRandomWordsForServerParams struct {
	ServerID         uuid.UUID   `json:"server_id"`
	N                int32       `json:"n"`
	OversampleByPerc pgtype.Int4 `json:"oversample_by_perc"`
}

type GetRandomWordsForServerRow struct {
	ID       uuid.UUID `json:"id"`
	ServerID uuid.UUID `json:"server_id"`
	Word     string    `json:"word"`
	AddedAt  time.Time `json:"added_at"`
}

func (q *Queries) GetRandomWordsForServer(ctx context.Context, arg GetRandomWordsForServerParams) ([]GetRandomWordsForServerRow, error) {
	rows, err := q.db.Query(ctx, getRandomWordsForServer, arg.ServerID, arg.N, arg.OversampleByPerc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRandomWordsForServerRow{}
	for rows.Next() {
		var i GetRandomWordsForServerRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Word,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWords = `-- name: ListWords :many
SELECT
    id,
    server_id,
    word,
    added_at
FROM words
WHERE server_id = $1
AND (
    $2::timestamptz IS NULL
    OR added_at < $2
    OR (added_at = $2 AND id < $3)
) ORDER BY added_at DESC, id DESC
LIMIT $4
`

type ListWordsParams struct {
	ServerID     uuid.UUID          `json:"server_id"`
	AfterAddedAt pgtype.Timestamptz `json:"after_added_at"`
	AfterID      pgtype.UUID        `json:"after_id"`
	PageSize     int32              `json:"page_size"`
}

type ListWordsRow struct {
	ID       uuid.UUID `json:"id"`
	ServerID uuid.UUID `json:"server_id"`
	Word     string    `json:"word"`
	AddedAt  time.Time `json:"added_at"`
}

func (q *Queries) ListWords(ctx context.Context, arg ListWordsParams) ([]ListWordsRow, error) {
	rows, err := q.db.Query(ctx, listWords,
		arg.ServerID,
		arg.AfterAddedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWordsRow{}
	for rows.Next() {
		var i ListWordsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Word,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllWordsFromServer = `-- name: RemoveAllWordsFromServer :execresult
DELETE FROM words
WHERE server_id = $1::uuid
`

func (q *Queries) RemoveAllWordsFromServer(ctx context.Context, serverID uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, removeAllWordsFromServer, serverID)
}

const removeWordsFromServer = `-- name: RemoveWordsFromServer :execresult
DELETE FROM words
WHERE server_id = $1::uuid
AND word = ANY($2::text[])
`

type RemoveWordsFromServerParams struct {
	ServerID uuid.UUID `json:"server_id"`
	Words    []string  `json:"words"`
}

func (q *Queries) RemoveWordsFromServer(ctx context.Context, arg RemoveWordsFromServerParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, removeWordsFromServer, arg.ServerID, arg.Words)
}
