syntax = "proto3";

package auth.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/spazzle-io/spazzle-api/services/auth/pb";

message GetSIWEPayloadRequest {
  string wallet_address = 1 [(buf.validate.field).required = true];
  string domain = 2 [(buf.validate.field).required = true];
  string uri = 3 [(buf.validate.field).required = true];
  uint32 chain_id = 4 [(buf.validate.field).required = true];
}

message GetSIWEPayloadResponse {
  string message = 1;
  string nonce = 2;
  string wallet_address = 3;
  google.protobuf.Timestamp issued_at = 4;
  google.protobuf.Timestamp expires_at = 5;
}

message AuthenticateRequest {
  string wallet_address = 1 [(buf.validate.field).required = true];
  string user_id = 2 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
  string signature = 3 [(buf.validate.field).required = true];
}

message AuthenticateResponse {
  Credential credential = 1;
  Session session = 2;
}

message RefreshAccessTokenRequest {
  string user_id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
  string wallet_address = 2 [(buf.validate.field).required = true];
}

message RefreshAccessTokenResponse {
  Session session = 1;
}

message RevokeRefreshTokensRequest {
  string user_id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
}

message RevokeRefreshTokensResponse {
  int64 num_sessions_revoked = 1;
}

message VerifyAccessTokenRequest {
  string user_id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
}

message VerifyAccessTokenResponse {
  AccessTokenPayload access_token_payload = 1;
}

message Credential {
  string id = 1;
  string user_id = 2;
  string wallet_address = 3;
  google.protobuf.Timestamp created_at = 4;
}

message Session {
  string session_id = 1;
  string access_token = 2;
  string refresh_token = 3;
  google.protobuf.Timestamp access_token_expires_at = 4;
  google.protobuf.Timestamp refresh_token_expires_at = 5;
  string token_type = 6;
}

message AccessTokenPayload {
  enum Role {
    ROLE_UNSPECIFIED = 0;
    ROLE_USER = 1;
    ROLE_ADMIN = 2;
  }

  string id = 1;
  string user_id = 2;
  string wallet_address = 3;
  Role role = 4;
  google.protobuf.Timestamp issued_at = 5;
  google.protobuf.Timestamp expires_at = 6;
}
