// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/rpc_service_auth.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessTokenPayload_Role int32

const (
	AccessTokenPayload_ROLE_UNSPECIFIED AccessTokenPayload_Role = 0
	AccessTokenPayload_ROLE_USER        AccessTokenPayload_Role = 1
	AccessTokenPayload_ROLE_ADMIN       AccessTokenPayload_Role = 2
)

// Enum value maps for AccessTokenPayload_Role.
var (
	AccessTokenPayload_Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ADMIN",
	}
	AccessTokenPayload_Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ADMIN":       2,
	}
)

func (x AccessTokenPayload_Role) Enum() *AccessTokenPayload_Role {
	p := new(AccessTokenPayload_Role)
	*p = x
	return p
}

func (x AccessTokenPayload_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessTokenPayload_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_rpc_service_auth_proto_enumTypes[0].Descriptor()
}

func (AccessTokenPayload_Role) Type() protoreflect.EnumType {
	return &file_auth_v1_rpc_service_auth_proto_enumTypes[0]
}

func (x AccessTokenPayload_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessTokenPayload_Role.Descriptor instead.
func (AccessTokenPayload_Role) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{12, 0}
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *AuthenticateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticateRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Session       *Session               `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *AuthenticateResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetSIWEPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSIWEPayloadRequest) Reset() {
	*x = GetSIWEPayloadRequest{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSIWEPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSIWEPayloadRequest) ProtoMessage() {}

func (x *GetSIWEPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSIWEPayloadRequest.ProtoReflect.Descriptor instead.
func (*GetSIWEPayloadRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GetSIWEPayloadRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetSIWEPayloadRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetSIWEPayloadRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type GetSIWEPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	WalletAddress string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	ChainId       uint32                 `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSIWEPayloadResponse) Reset() {
	*x = GetSIWEPayloadResponse{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSIWEPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSIWEPayloadResponse) ProtoMessage() {}

func (x *GetSIWEPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSIWEPayloadResponse.ProtoReflect.Descriptor instead.
func (*GetSIWEPayloadResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetSIWEPayloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSIWEPayloadResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *GetSIWEPayloadResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetSIWEPayloadResponse) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetSIWEPayloadResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *GetSIWEPayloadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RefreshAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAccessTokenRequest) Reset() {
	*x = RefreshAccessTokenRequest{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenRequest) ProtoMessage() {}

func (x *RefreshAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{4}
}

type RefreshAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAccessTokenResponse) Reset() {
	*x = RefreshAccessTokenResponse{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenResponse) ProtoMessage() {}

func (x *RefreshAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshAccessTokenResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type RevokeRefreshTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshTokensRequest) Reset() {
	*x = RevokeRefreshTokensRequest{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshTokensRequest) ProtoMessage() {}

func (x *RevokeRefreshTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshTokensRequest.ProtoReflect.Descriptor instead.
func (*RevokeRefreshTokensRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{6}
}

type RevokeRefreshTokensResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NumSessionsRevoked int64                  `protobuf:"varint,1,opt,name=num_sessions_revoked,json=numSessionsRevoked,proto3" json:"num_sessions_revoked,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RevokeRefreshTokensResponse) Reset() {
	*x = RevokeRefreshTokensResponse{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshTokensResponse) ProtoMessage() {}

func (x *RevokeRefreshTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshTokensResponse.ProtoReflect.Descriptor instead.
func (*RevokeRefreshTokensResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeRefreshTokensResponse) GetNumSessionsRevoked() int64 {
	if x != nil {
		return x.NumSessionsRevoked
	}
	return 0
}

type VerifyAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessTokenRequest) Reset() {
	*x = VerifyAccessTokenRequest{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenRequest) ProtoMessage() {}

func (x *VerifyAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{8}
}

type VerifyAccessTokenResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessTokenPayload *AccessTokenPayload    `protobuf:"bytes,1,opt,name=access_token_payload,json=accessTokenPayload,proto3" json:"access_token_payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerifyAccessTokenResponse) Reset() {
	*x = VerifyAccessTokenResponse{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenResponse) ProtoMessage() {}

func (x *VerifyAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyAccessTokenResponse) GetAccessTokenPayload() *AccessTokenPayload {
	if x != nil {
		return x.AccessTokenPayload
	}
	return nil
}

type Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{10}
}

func (x *Credential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Credential) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Credential) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *Credential) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Session struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SessionId             string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessToken           string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	TokenType             string                 `protobuf:"bytes,6,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{11}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Session) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Session) GetAccessTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return nil
}

func (x *Session) GetRefreshTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return nil
}

func (x *Session) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type AccessTokenPayload struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress string                  `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Role          AccessTokenPayload_Role `protobuf:"varint,4,opt,name=role,proto3,enum=auth.v1.AccessTokenPayload_Role" json:"role,omitempty"`
	IssuedAt      *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenPayload) Reset() {
	*x = AccessTokenPayload{}
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenPayload) ProtoMessage() {}

func (x *AccessTokenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_service_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenPayload.ProtoReflect.Descriptor instead.
func (*AccessTokenPayload) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_service_auth_proto_rawDescGZIP(), []int{12}
}

func (x *AccessTokenPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessTokenPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessTokenPayload) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *AccessTokenPayload) GetRole() AccessTokenPayload_Role {
	if x != nil {
		return x.Role
	}
	return AccessTokenPayload_ROLE_UNSPECIFIED
}

func (x *AccessTokenPayload) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *AccessTokenPayload) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_auth_v1_rpc_service_auth_proto protoreflect.FileDescriptor

const file_auth_v1_rpc_service_auth_proto_rawDesc = "" +
	"\n" +
	"\x1eauth/v1/rpc_service_auth.proto\x12\aauth.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x13AuthenticateRequest\x12-\n" +
	"\x0ewallet_address\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\rwalletAddress\x12$\n" +
	"\auser_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06userId\x12$\n" +
	"\tsignature\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tsignature\"w\n" +
	"\x14AuthenticateResponse\x123\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x13.auth.v1.CredentialR\n" +
	"credential\x12*\n" +
	"\asession\x18\x02 \x01(\v2\x10.auth.v1.SessionR\asession\"\x80\x01\n" +
	"\x15GetSIWEPayloadRequest\x12-\n" +
	"\x0ewallet_address\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\rwalletAddress\x12\x1e\n" +
	"\x06domain\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06domain\x12\x18\n" +
	"\x03uri\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03uri\"\xfe\x01\n" +
	"\x16GetSIWEPayloadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\rR\achainId\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x1b\n" +
	"\x19RefreshAccessTokenRequest\"H\n" +
	"\x1aRefreshAccessTokenResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.auth.v1.SessionR\asession\"\x1c\n" +
	"\x1aRevokeRefreshTokensRequest\"O\n" +
	"\x1bRevokeRefreshTokensResponse\x120\n" +
	"\x14num_sessions_revoked\x18\x01 \x01(\x03R\x12numSessionsRevoked\"\x1a\n" +
	"\x18VerifyAccessTokenRequest\"j\n" +
	"\x19VerifyAccessTokenResponse\x12M\n" +
	"\x14access_token_payload\x18\x01 \x01(\v2\x1b.auth.v1.AccessTokenPayloadR\x12accessTokenPayload\"\x97\x01\n" +
	"\n" +
	"Credential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb7\x02\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12Q\n" +
	"\x17access_token_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x14accessTokenExpiresAt\x12S\n" +
	"\x18refresh_token_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x15refreshTokenExpiresAt\x12\x1d\n" +
	"\n" +
	"token_type\x18\x06 \x01(\tR\ttokenType\"\xcb\x02\n" +
	"\x12AccessTokenPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\x124\n" +
	"\x04role\x18\x04 \x01(\x0e2 .auth.v1.AccessTokenPayload.RoleR\x04role\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\";\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02B\x93\x01\n" +
	"\vcom.auth.v1B\x13RpcServiceAuthProtoP\x01Z2github.com/spazzle-io/spazzle-api/services/auth/pb\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1b\x06proto3"

var (
	file_auth_v1_rpc_service_auth_proto_rawDescOnce sync.Once
	file_auth_v1_rpc_service_auth_proto_rawDescData []byte
)

func file_auth_v1_rpc_service_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_rpc_service_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_rpc_service_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_rpc_service_auth_proto_rawDesc), len(file_auth_v1_rpc_service_auth_proto_rawDesc)))
	})
	return file_auth_v1_rpc_service_auth_proto_rawDescData
}

var file_auth_v1_rpc_service_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_rpc_service_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_auth_v1_rpc_service_auth_proto_goTypes = []any{
	(AccessTokenPayload_Role)(0),        // 0: auth.v1.AccessTokenPayload.Role
	(*AuthenticateRequest)(nil),         // 1: auth.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),        // 2: auth.v1.AuthenticateResponse
	(*GetSIWEPayloadRequest)(nil),       // 3: auth.v1.GetSIWEPayloadRequest
	(*GetSIWEPayloadResponse)(nil),      // 4: auth.v1.GetSIWEPayloadResponse
	(*RefreshAccessTokenRequest)(nil),   // 5: auth.v1.RefreshAccessTokenRequest
	(*RefreshAccessTokenResponse)(nil),  // 6: auth.v1.RefreshAccessTokenResponse
	(*RevokeRefreshTokensRequest)(nil),  // 7: auth.v1.RevokeRefreshTokensRequest
	(*RevokeRefreshTokensResponse)(nil), // 8: auth.v1.RevokeRefreshTokensResponse
	(*VerifyAccessTokenRequest)(nil),    // 9: auth.v1.VerifyAccessTokenRequest
	(*VerifyAccessTokenResponse)(nil),   // 10: auth.v1.VerifyAccessTokenResponse
	(*Credential)(nil),                  // 11: auth.v1.Credential
	(*Session)(nil),                     // 12: auth.v1.Session
	(*AccessTokenPayload)(nil),          // 13: auth.v1.AccessTokenPayload
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
}
var file_auth_v1_rpc_service_auth_proto_depIdxs = []int32{
	11, // 0: auth.v1.AuthenticateResponse.credential:type_name -> auth.v1.Credential
	12, // 1: auth.v1.AuthenticateResponse.session:type_name -> auth.v1.Session
	14, // 2: auth.v1.GetSIWEPayloadResponse.issued_at:type_name -> google.protobuf.Timestamp
	14, // 3: auth.v1.GetSIWEPayloadResponse.expires_at:type_name -> google.protobuf.Timestamp
	12, // 4: auth.v1.RefreshAccessTokenResponse.session:type_name -> auth.v1.Session
	13, // 5: auth.v1.VerifyAccessTokenResponse.access_token_payload:type_name -> auth.v1.AccessTokenPayload
	14, // 6: auth.v1.Credential.created_at:type_name -> google.protobuf.Timestamp
	14, // 7: auth.v1.Session.access_token_expires_at:type_name -> google.protobuf.Timestamp
	14, // 8: auth.v1.Session.refresh_token_expires_at:type_name -> google.protobuf.Timestamp
	0,  // 9: auth.v1.AccessTokenPayload.role:type_name -> auth.v1.AccessTokenPayload.Role
	14, // 10: auth.v1.AccessTokenPayload.issued_at:type_name -> google.protobuf.Timestamp
	14, // 11: auth.v1.AccessTokenPayload.expires_at:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_auth_v1_rpc_service_auth_proto_init() }
func file_auth_v1_rpc_service_auth_proto_init() {
	if File_auth_v1_rpc_service_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_rpc_service_auth_proto_rawDesc), len(file_auth_v1_rpc_service_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_rpc_service_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_rpc_service_auth_proto_depIdxs,
		EnumInfos:         file_auth_v1_rpc_service_auth_proto_enumTypes,
		MessageInfos:      file_auth_v1_rpc_service_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_rpc_service_auth_proto = out.File
	file_auth_v1_rpc_service_auth_proto_goTypes = nil
	file_auth_v1_rpc_service_auth_proto_depIdxs = nil
}
