// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: auth/v1/rpc_authenticate.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_auth_v1_rpc_authenticate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_authenticate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_authenticate_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *AuthenticateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticateRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Session       *Session               `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_auth_v1_rpc_authenticate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_authenticate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_authenticate_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *AuthenticateResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_auth_v1_rpc_authenticate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_rpc_authenticate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_auth_v1_rpc_authenticate_proto_rawDescGZIP(), []int{2}
}

func (x *Credential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Credential) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Credential) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *Credential) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_auth_v1_rpc_authenticate_proto protoreflect.FileDescriptor

const file_auth_v1_rpc_authenticate_proto_rawDesc = "" +
	"\n" +
	"\x1eauth/v1/rpc_authenticate.proto\x12\aauth.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14auth/v1/common.proto\"\x90\x01\n" +
	"\x13AuthenticateRequest\x12-\n" +
	"\x0ewallet_address\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\rwalletAddress\x12$\n" +
	"\auser_id\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06userId\x12$\n" +
	"\tsignature\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tsignature\"w\n" +
	"\x14AuthenticateResponse\x123\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x13.auth.v1.CredentialR\n" +
	"credential\x12*\n" +
	"\asession\x18\x02 \x01(\v2\x10.auth.v1.SessionR\asession\"\x97\x01\n" +
	"\n" +
	"Credential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x94\x01\n" +
	"\vcom.auth.v1B\x14RpcAuthenticateProtoP\x01Z2github.com/spazzle-io/spazzle-api/services/auth/pb\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1b\x06proto3"

var (
	file_auth_v1_rpc_authenticate_proto_rawDescOnce sync.Once
	file_auth_v1_rpc_authenticate_proto_rawDescData []byte
)

func file_auth_v1_rpc_authenticate_proto_rawDescGZIP() []byte {
	file_auth_v1_rpc_authenticate_proto_rawDescOnce.Do(func() {
		file_auth_v1_rpc_authenticate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_rpc_authenticate_proto_rawDesc), len(file_auth_v1_rpc_authenticate_proto_rawDesc)))
	})
	return file_auth_v1_rpc_authenticate_proto_rawDescData
}

var file_auth_v1_rpc_authenticate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_v1_rpc_authenticate_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),   // 0: auth.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),  // 1: auth.v1.AuthenticateResponse
	(*Credential)(nil),            // 2: auth.v1.Credential
	(*Session)(nil),               // 3: auth.v1.Session
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_auth_v1_rpc_authenticate_proto_depIdxs = []int32{
	2, // 0: auth.v1.AuthenticateResponse.credential:type_name -> auth.v1.Credential
	3, // 1: auth.v1.AuthenticateResponse.session:type_name -> auth.v1.Session
	4, // 2: auth.v1.Credential.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_v1_rpc_authenticate_proto_init() }
func file_auth_v1_rpc_authenticate_proto_init() {
	if File_auth_v1_rpc_authenticate_proto != nil {
		return
	}
	file_auth_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_rpc_authenticate_proto_rawDesc), len(file_auth_v1_rpc_authenticate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_rpc_authenticate_proto_goTypes,
		DependencyIndexes: file_auth_v1_rpc_authenticate_proto_depIdxs,
		MessageInfos:      file_auth_v1_rpc_authenticate_proto_msgTypes,
	}.Build()
	File_auth_v1_rpc_authenticate_proto = out.File
	file_auth_v1_rpc_authenticate_proto_goTypes = nil
	file_auth_v1_rpc_authenticate_proto_depIdxs = nil
}
