// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: auth/v1/service_auth.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_v1_service_auth_proto protoreflect.FileDescriptor

const file_auth_v1_service_auth_proto_rawDesc = "" +
	"\n" +
	"\x1aauth/v1/service_auth.proto\x12\aauth.v1\x1a\"auth/v1/rpc_get_siwe_payload.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xa3\x02\n" +
	"\vAuthService\x12\x93\x02\n" +
	"\x0eGetSIWEPayload\x12\x1e.auth.v1.GetSIWEPayloadRequest\x1a\x1f.auth.v1.GetSIWEPayloadResponse\"\xbf\x01\x92A\xa1\x01\x127Generate SIWE message payload for EVM compatible chains\x1adGenerates a Sign-In With Ethereum (SIWE) message payload for the specified wallet address and domainb\x00\x82\xd3\xe4\x93\x02\x14\x12\x12/auth/siwe-payloadB\xaf\x02\x92A\x9b\x01\x120\n" +
	"\fAuth Service\"\x1d\n" +
	"\aSpazzle\x12\x12https://spazzle.io2\x010ZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\n" +
	"\vcom.auth.v1B\x10ServiceAuthProtoP\x01Z2github.com/spazzle-io/spazzle-api/services/auth/pb\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1b\x06proto3"

var file_auth_v1_service_auth_proto_goTypes = []any{
	(*GetSIWEPayloadRequest)(nil),  // 0: auth.v1.GetSIWEPayloadRequest
	(*GetSIWEPayloadResponse)(nil), // 1: auth.v1.GetSIWEPayloadResponse
}
var file_auth_v1_service_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.GetSIWEPayload:input_type -> auth.v1.GetSIWEPayloadRequest
	1, // 1: auth.v1.AuthService.GetSIWEPayload:output_type -> auth.v1.GetSIWEPayloadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_service_auth_proto_init() }
func file_auth_v1_service_auth_proto_init() {
	if File_auth_v1_service_auth_proto != nil {
		return
	}
	file_auth_v1_rpc_get_siwe_payload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_service_auth_proto_rawDesc), len(file_auth_v1_service_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_service_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_service_auth_proto_depIdxs,
	}.Build()
	File_auth_v1_service_auth_proto = out.File
	file_auth_v1_service_auth_proto_goTypes = nil
	file_auth_v1_service_auth_proto_depIdxs = nil
}
