Project users_service {
  database_type: 'PostgreSQL'
  Note: '''
    # Users Service Database
  '''
}

Table users {
  id UUID [default: `gen_random_uuid()`, pk]
  wallet_address text [unique, not null]
  gamer_tag text [unique]
  created_at timestamptz [not null, default: `now()`]

  indexes {
    wallet_address
  }
}
