DROP TABLE IF EXISTS words;
DROP TABLE IF EXISTS server_admins;
DROP TABLE IF EXISTS server_player_stats;
DROP TABLE IF EXISTS game_players;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS user_stats;
DROP TABLE IF EXISTS servers;
