// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spazzle-io/spazzle-api/services/gameplay/internal/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package=mockdb --destination=internal/db/mock/store.go github.com/spazzle-io/spazzle-api/services/gameplay/internal/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	db "github.com/spazzle-io/spazzle-api/services/gameplay/internal/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddServerAdmin mocks base method.
func (m *MockStore) AddServerAdmin(ctx context.Context, arg db.AddServerAdminParams) (db.ServerAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddServerAdmin", ctx, arg)
	ret0, _ := ret[0].(db.ServerAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddServerAdmin indicates an expected call of AddServerAdmin.
func (mr *MockStoreMockRecorder) AddServerAdmin(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddServerAdmin", reflect.TypeOf((*MockStore)(nil).AddServerAdmin), ctx, arg)
}

// AddServerAdminTx mocks base method.
func (m *MockStore) AddServerAdminTx(ctx context.Context, params db.AddServerAdminTxParams) (db.AddServerAdminTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddServerAdminTx", ctx, params)
	ret0, _ := ret[0].(db.AddServerAdminTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddServerAdminTx indicates an expected call of AddServerAdminTx.
func (mr *MockStoreMockRecorder) AddServerAdminTx(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddServerAdminTx", reflect.TypeOf((*MockStore)(nil).AddServerAdminTx), ctx, params)
}

// AddServerWordsTx mocks base method.
func (m *MockStore) AddServerWordsTx(ctx context.Context, params db.AddServerWordsTxParams) (db.AddServerWordsTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddServerWordsTx", ctx, params)
	ret0, _ := ret[0].(db.AddServerWordsTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddServerWordsTx indicates an expected call of AddServerWordsTx.
func (mr *MockStoreMockRecorder) AddServerWordsTx(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddServerWordsTx", reflect.TypeOf((*MockStore)(nil).AddServerWordsTx), ctx, params)
}

// AddWordsToServer mocks base method.
func (m *MockStore) AddWordsToServer(ctx context.Context, arg db.AddWordsToServerParams) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWordsToServer", ctx, arg)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddWordsToServer indicates an expected call of AddWordsToServer.
func (mr *MockStoreMockRecorder) AddWordsToServer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWordsToServer", reflect.TypeOf((*MockStore)(nil).AddWordsToServer), ctx, arg)
}

// CreateGame mocks base method.
func (m *MockStore) CreateGame(ctx context.Context, arg db.CreateGameParams) (db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGame", ctx, arg)
	ret0, _ := ret[0].(db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGame indicates an expected call of CreateGame.
func (mr *MockStoreMockRecorder) CreateGame(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGame", reflect.TypeOf((*MockStore)(nil).CreateGame), ctx, arg)
}

// CreateServer mocks base method.
func (m *MockStore) CreateServer(ctx context.Context, arg db.CreateServerParams) (db.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServer", ctx, arg)
	ret0, _ := ret[0].(db.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServer indicates an expected call of CreateServer.
func (mr *MockStoreMockRecorder) CreateServer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServer", reflect.TypeOf((*MockStore)(nil).CreateServer), ctx, arg)
}

// GetGameById mocks base method.
func (m *MockStore) GetGameById(ctx context.Context, gameID uuid.UUID) (db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameById", ctx, gameID)
	ret0, _ := ret[0].(db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameById indicates an expected call of GetGameById.
func (mr *MockStoreMockRecorder) GetGameById(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameById", reflect.TypeOf((*MockStore)(nil).GetGameById), ctx, gameID)
}

// GetGameLeaderboard mocks base method.
func (m *MockStore) GetGameLeaderboard(ctx context.Context, arg db.GetGameLeaderboardParams) ([]db.GamePlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameLeaderboard", ctx, arg)
	ret0, _ := ret[0].([]db.GamePlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameLeaderboard indicates an expected call of GetGameLeaderboard.
func (mr *MockStoreMockRecorder) GetGameLeaderboard(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameLeaderboard", reflect.TypeOf((*MockStore)(nil).GetGameLeaderboard), ctx, arg)
}

// GetGlobalLeaderboard mocks base method.
func (m *MockStore) GetGlobalLeaderboard(ctx context.Context, arg db.GetGlobalLeaderboardParams) ([]db.UserStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalLeaderboard", ctx, arg)
	ret0, _ := ret[0].([]db.UserStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalLeaderboard indicates an expected call of GetGlobalLeaderboard.
func (mr *MockStoreMockRecorder) GetGlobalLeaderboard(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalLeaderboard", reflect.TypeOf((*MockStore)(nil).GetGlobalLeaderboard), ctx, arg)
}

// GetRandomWordsForServer mocks base method.
func (m *MockStore) GetRandomWordsForServer(ctx context.Context, arg db.GetRandomWordsForServerParams) ([]db.GetRandomWordsForServerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomWordsForServer", ctx, arg)
	ret0, _ := ret[0].([]db.GetRandomWordsForServerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomWordsForServer indicates an expected call of GetRandomWordsForServer.
func (mr *MockStoreMockRecorder) GetRandomWordsForServer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomWordsForServer", reflect.TypeOf((*MockStore)(nil).GetRandomWordsForServer), ctx, arg)
}

// GetServerById mocks base method.
func (m *MockStore) GetServerById(ctx context.Context, serverID uuid.UUID) (db.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerById", ctx, serverID)
	ret0, _ := ret[0].(db.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerById indicates an expected call of GetServerById.
func (mr *MockStoreMockRecorder) GetServerById(ctx, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerById", reflect.TypeOf((*MockStore)(nil).GetServerById), ctx, serverID)
}

// GetServerByName mocks base method.
func (m *MockStore) GetServerByName(ctx context.Context, name string) (db.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerByName", ctx, name)
	ret0, _ := ret[0].(db.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerByName indicates an expected call of GetServerByName.
func (mr *MockStoreMockRecorder) GetServerByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerByName", reflect.TypeOf((*MockStore)(nil).GetServerByName), ctx, name)
}

// GetServerLeaderboard mocks base method.
func (m *MockStore) GetServerLeaderboard(ctx context.Context, arg db.GetServerLeaderboardParams) ([]db.ServerPlayerStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerLeaderboard", ctx, arg)
	ret0, _ := ret[0].([]db.ServerPlayerStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerLeaderboard indicates an expected call of GetServerLeaderboard.
func (mr *MockStoreMockRecorder) GetServerLeaderboard(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerLeaderboard", reflect.TypeOf((*MockStore)(nil).GetServerLeaderboard), ctx, arg)
}

// GetServerUserPermissions mocks base method.
func (m *MockStore) GetServerUserPermissions(ctx context.Context, arg db.GetServerUserPermissionsParams) (db.GetServerUserPermissionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerUserPermissions", ctx, arg)
	ret0, _ := ret[0].(db.GetServerUserPermissionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerUserPermissions indicates an expected call of GetServerUserPermissions.
func (mr *MockStoreMockRecorder) GetServerUserPermissions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerUserPermissions", reflect.TypeOf((*MockStore)(nil).GetServerUserPermissions), ctx, arg)
}

// GetTotalGamePlayersCount mocks base method.
func (m *MockStore) GetTotalGamePlayersCount(ctx context.Context, gameID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalGamePlayersCount", ctx, gameID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalGamePlayersCount indicates an expected call of GetTotalGamePlayersCount.
func (mr *MockStoreMockRecorder) GetTotalGamePlayersCount(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalGamePlayersCount", reflect.TypeOf((*MockStore)(nil).GetTotalGamePlayersCount), ctx, gameID)
}

// GetTotalServerCount mocks base method.
func (m *MockStore) GetTotalServerCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalServerCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalServerCount indicates an expected call of GetTotalServerCount.
func (mr *MockStoreMockRecorder) GetTotalServerCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalServerCount", reflect.TypeOf((*MockStore)(nil).GetTotalServerCount), ctx)
}

// GetTotalServerGamesCount mocks base method.
func (m *MockStore) GetTotalServerGamesCount(ctx context.Context, serverID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalServerGamesCount", ctx, serverID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalServerGamesCount indicates an expected call of GetTotalServerGamesCount.
func (mr *MockStoreMockRecorder) GetTotalServerGamesCount(ctx, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalServerGamesCount", reflect.TypeOf((*MockStore)(nil).GetTotalServerGamesCount), ctx, serverID)
}

// GetTotalServerPlayerStatsCount mocks base method.
func (m *MockStore) GetTotalServerPlayerStatsCount(ctx context.Context, serverID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalServerPlayerStatsCount", ctx, serverID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalServerPlayerStatsCount indicates an expected call of GetTotalServerPlayerStatsCount.
func (mr *MockStoreMockRecorder) GetTotalServerPlayerStatsCount(ctx, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalServerPlayerStatsCount", reflect.TypeOf((*MockStore)(nil).GetTotalServerPlayerStatsCount), ctx, serverID)
}

// GetTotalUserGamesCount mocks base method.
func (m *MockStore) GetTotalUserGamesCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalUserGamesCount", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalUserGamesCount indicates an expected call of GetTotalUserGamesCount.
func (mr *MockStoreMockRecorder) GetTotalUserGamesCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalUserGamesCount", reflect.TypeOf((*MockStore)(nil).GetTotalUserGamesCount), ctx, userID)
}

// GetTotalUserServersCount mocks base method.
func (m *MockStore) GetTotalUserServersCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalUserServersCount", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalUserServersCount indicates an expected call of GetTotalUserServersCount.
func (mr *MockStoreMockRecorder) GetTotalUserServersCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalUserServersCount", reflect.TypeOf((*MockStore)(nil).GetTotalUserServersCount), ctx, userID)
}

// GetTotalUserStatsCount mocks base method.
func (m *MockStore) GetTotalUserStatsCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalUserStatsCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalUserStatsCount indicates an expected call of GetTotalUserStatsCount.
func (mr *MockStoreMockRecorder) GetTotalUserStatsCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalUserStatsCount", reflect.TypeOf((*MockStore)(nil).GetTotalUserStatsCount), ctx)
}

// GetUserStats mocks base method.
func (m *MockStore) GetUserStats(ctx context.Context, userID uuid.UUID) (db.UserStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStats", ctx, userID)
	ret0, _ := ret[0].(db.UserStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStats indicates an expected call of GetUserStats.
func (mr *MockStoreMockRecorder) GetUserStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStats", reflect.TypeOf((*MockStore)(nil).GetUserStats), ctx, userID)
}

// InsertGamePlayers mocks base method.
func (m *MockStore) InsertGamePlayers(ctx context.Context, arg []db.InsertGamePlayersParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertGamePlayers", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertGamePlayers indicates an expected call of InsertGamePlayers.
func (mr *MockStoreMockRecorder) InsertGamePlayers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertGamePlayers", reflect.TypeOf((*MockStore)(nil).InsertGamePlayers), ctx, arg)
}

// ListServerAdmins mocks base method.
func (m *MockStore) ListServerAdmins(ctx context.Context, arg db.ListServerAdminsParams) ([]db.ServerAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServerAdmins", ctx, arg)
	ret0, _ := ret[0].([]db.ServerAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServerAdmins indicates an expected call of ListServerAdmins.
func (mr *MockStoreMockRecorder) ListServerAdmins(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServerAdmins", reflect.TypeOf((*MockStore)(nil).ListServerAdmins), ctx, arg)
}

// ListServerGames mocks base method.
func (m *MockStore) ListServerGames(ctx context.Context, arg db.ListServerGamesParams) ([]db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServerGames", ctx, arg)
	ret0, _ := ret[0].([]db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServerGames indicates an expected call of ListServerGames.
func (mr *MockStoreMockRecorder) ListServerGames(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServerGames", reflect.TypeOf((*MockStore)(nil).ListServerGames), ctx, arg)
}

// ListServers mocks base method.
func (m *MockStore) ListServers(ctx context.Context, arg db.ListServersParams) ([]db.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServers", ctx, arg)
	ret0, _ := ret[0].([]db.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServers indicates an expected call of ListServers.
func (mr *MockStoreMockRecorder) ListServers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServers", reflect.TypeOf((*MockStore)(nil).ListServers), ctx, arg)
}

// ListServersByPopular mocks base method.
func (m *MockStore) ListServersByPopular(ctx context.Context, arg db.ListServersByPopularParams) ([]db.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServersByPopular", ctx, arg)
	ret0, _ := ret[0].([]db.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServersByPopular indicates an expected call of ListServersByPopular.
func (mr *MockStoreMockRecorder) ListServersByPopular(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServersByPopular", reflect.TypeOf((*MockStore)(nil).ListServersByPopular), ctx, arg)
}

// ListServersByTrending mocks base method.
func (m *MockStore) ListServersByTrending(ctx context.Context, arg db.ListServersByTrendingParams) ([]db.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServersByTrending", ctx, arg)
	ret0, _ := ret[0].([]db.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServersByTrending indicates an expected call of ListServersByTrending.
func (mr *MockStoreMockRecorder) ListServersByTrending(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServersByTrending", reflect.TypeOf((*MockStore)(nil).ListServersByTrending), ctx, arg)
}

// ListUserGames mocks base method.
func (m *MockStore) ListUserGames(ctx context.Context, arg db.ListUserGamesParams) ([]db.ListUserGamesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserGames", ctx, arg)
	ret0, _ := ret[0].([]db.ListUserGamesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserGames indicates an expected call of ListUserGames.
func (mr *MockStoreMockRecorder) ListUserGames(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserGames", reflect.TypeOf((*MockStore)(nil).ListUserGames), ctx, arg)
}

// ListUserServers mocks base method.
func (m *MockStore) ListUserServers(ctx context.Context, arg db.ListUserServersParams) ([]db.ListUserServersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserServers", ctx, arg)
	ret0, _ := ret[0].([]db.ListUserServersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserServers indicates an expected call of ListUserServers.
func (mr *MockStoreMockRecorder) ListUserServers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserServers", reflect.TypeOf((*MockStore)(nil).ListUserServers), ctx, arg)
}

// ListWords mocks base method.
func (m *MockStore) ListWords(ctx context.Context, arg db.ListWordsParams) ([]db.ListWordsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWords", ctx, arg)
	ret0, _ := ret[0].([]db.ListWordsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWords indicates an expected call of ListWords.
func (mr *MockStoreMockRecorder) ListWords(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWords", reflect.TypeOf((*MockStore)(nil).ListWords), ctx, arg)
}

// RecomputeTrendingScores mocks base method.
func (m *MockStore) RecomputeTrendingScores(ctx context.Context, trendingWindow pgtype.Interval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecomputeTrendingScores", ctx, trendingWindow)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecomputeTrendingScores indicates an expected call of RecomputeTrendingScores.
func (mr *MockStoreMockRecorder) RecomputeTrendingScores(ctx, trendingWindow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecomputeTrendingScores", reflect.TypeOf((*MockStore)(nil).RecomputeTrendingScores), ctx, trendingWindow)
}

// RemoveAllServerWordsTx mocks base method.
func (m *MockStore) RemoveAllServerWordsTx(ctx context.Context, serverId uuid.UUID) (db.RemoveAllServerWordsTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllServerWordsTx", ctx, serverId)
	ret0, _ := ret[0].(db.RemoveAllServerWordsTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAllServerWordsTx indicates an expected call of RemoveAllServerWordsTx.
func (mr *MockStoreMockRecorder) RemoveAllServerWordsTx(ctx, serverId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllServerWordsTx", reflect.TypeOf((*MockStore)(nil).RemoveAllServerWordsTx), ctx, serverId)
}

// RemoveAllWordsFromServer mocks base method.
func (m *MockStore) RemoveAllWordsFromServer(ctx context.Context, serverID uuid.UUID) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllWordsFromServer", ctx, serverID)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAllWordsFromServer indicates an expected call of RemoveAllWordsFromServer.
func (mr *MockStoreMockRecorder) RemoveAllWordsFromServer(ctx, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllWordsFromServer", reflect.TypeOf((*MockStore)(nil).RemoveAllWordsFromServer), ctx, serverID)
}

// RemoveServerAdmin mocks base method.
func (m *MockStore) RemoveServerAdmin(ctx context.Context, arg db.RemoveServerAdminParams) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveServerAdmin", ctx, arg)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveServerAdmin indicates an expected call of RemoveServerAdmin.
func (mr *MockStoreMockRecorder) RemoveServerAdmin(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveServerAdmin", reflect.TypeOf((*MockStore)(nil).RemoveServerAdmin), ctx, arg)
}

// RemoveServerAdminTx mocks base method.
func (m *MockStore) RemoveServerAdminTx(ctx context.Context, params db.RemoveServerAdminTxParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveServerAdminTx", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveServerAdminTx indicates an expected call of RemoveServerAdminTx.
func (mr *MockStoreMockRecorder) RemoveServerAdminTx(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveServerAdminTx", reflect.TypeOf((*MockStore)(nil).RemoveServerAdminTx), ctx, params)
}

// RemoveServerWordsTx mocks base method.
func (m *MockStore) RemoveServerWordsTx(ctx context.Context, params db.RemoveServerWordsTxParams) (db.RemoveServerWordsTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveServerWordsTx", ctx, params)
	ret0, _ := ret[0].(db.RemoveServerWordsTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveServerWordsTx indicates an expected call of RemoveServerWordsTx.
func (mr *MockStoreMockRecorder) RemoveServerWordsTx(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveServerWordsTx", reflect.TypeOf((*MockStore)(nil).RemoveServerWordsTx), ctx, params)
}

// RemoveWordsFromServer mocks base method.
func (m *MockStore) RemoveWordsFromServer(ctx context.Context, arg db.RemoveWordsFromServerParams) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWordsFromServer", ctx, arg)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveWordsFromServer indicates an expected call of RemoveWordsFromServer.
func (mr *MockStoreMockRecorder) RemoveWordsFromServer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWordsFromServer", reflect.TypeOf((*MockStore)(nil).RemoveWordsFromServer), ctx, arg)
}

// ResetTrendingScores mocks base method.
func (m *MockStore) ResetTrendingScores(ctx context.Context, trendingWindow pgtype.Interval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetTrendingScores", ctx, trendingWindow)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetTrendingScores indicates an expected call of ResetTrendingScores.
func (mr *MockStoreMockRecorder) ResetTrendingScores(ctx, trendingWindow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetTrendingScores", reflect.TypeOf((*MockStore)(nil).ResetTrendingScores), ctx, trendingWindow)
}

// UpdateServer mocks base method.
func (m *MockStore) UpdateServer(ctx context.Context, arg db.UpdateServerParams) (db.Server, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServer", ctx, arg)
	ret0, _ := ret[0].(db.Server)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServer indicates an expected call of UpdateServer.
func (mr *MockStoreMockRecorder) UpdateServer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServer", reflect.TypeOf((*MockStore)(nil).UpdateServer), ctx, arg)
}

// UpdateServerGameStats mocks base method.
func (m *MockStore) UpdateServerGameStats(ctx context.Context, arg db.UpdateServerGameStatsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServerGameStats", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServerGameStats indicates an expected call of UpdateServerGameStats.
func (mr *MockStoreMockRecorder) UpdateServerGameStats(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServerGameStats", reflect.TypeOf((*MockStore)(nil).UpdateServerGameStats), ctx, arg)
}

// UpsertServerPlayerStats mocks base method.
func (m *MockStore) UpsertServerPlayerStats(ctx context.Context, arg db.UpsertServerPlayerStatsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertServerPlayerStats", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertServerPlayerStats indicates an expected call of UpsertServerPlayerStats.
func (mr *MockStoreMockRecorder) UpsertServerPlayerStats(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertServerPlayerStats", reflect.TypeOf((*MockStore)(nil).UpsertServerPlayerStats), ctx, arg)
}

// UpsertUserStats mocks base method.
func (m *MockStore) UpsertUserStats(ctx context.Context, arg db.UpsertUserStatsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserStats", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserStats indicates an expected call of UpsertUserStats.
func (mr *MockStoreMockRecorder) UpsertUserStats(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserStats", reflect.TypeOf((*MockStore)(nil).UpsertUserStats), ctx, arg)
}
