// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spazzle-io/spazzle-api/services/gameplay/internal/worker (interfaces: TaskDistributor)
//
// Generated by this command:
//
//	mockgen -package=mockworker --destination=internal/worker/mock/distributor.go github.com/spazzle-io/spazzle-api/services/gameplay/internal/worker TaskDistributor
//

// Package mockworker is a generated GoMock package.
package mockworker

import (
	context "context"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	worker "github.com/spazzle-io/spazzle-api/services/gameplay/internal/worker"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
	isgomock struct{}
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTaskDistributor) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTaskDistributorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTaskDistributor)(nil).Close))
}

// DistributeTaskArchiveGame mocks base method.
func (m *MockTaskDistributor) DistributeTaskArchiveGame(ctx context.Context, payload *worker.PayloadArchiveGame, opts ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, payload}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskArchiveGame", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskArchiveGame indicates an expected call of DistributeTaskArchiveGame.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskArchiveGame(ctx, payload any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, payload}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskArchiveGame", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskArchiveGame), varargs...)
}

// DistributeTaskDeployTreasury mocks base method.
func (m *MockTaskDistributor) DistributeTaskDeployTreasury(ctx context.Context, payload *worker.PayloadDeployTreasury, opts ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, payload}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskDeployTreasury", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskDeployTreasury indicates an expected call of DistributeTaskDeployTreasury.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskDeployTreasury(ctx, payload any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, payload}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskDeployTreasury", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskDeployTreasury), varargs...)
}
