mock:
	mockgen -package=mockcache --destination=cache/mock/cache.go github.com/spazzle-io/spazzle-api/libs/common/cache Cache
	mockgen -package=mockstorage --destination=storage/mock/storage.go github.com/spazzle-io/spazzle-api/libs/common/storage ObjectStore

.PHONY: mock
