syntax = "proto3";

package gameplay.v1;

import "buf/validate/validate.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/spazzle-io/spazzle-api/services/gameplay/pb";

message CreateServerRequest {
  string name = 1 [(buf.validate.field).required = true];
  string stake_per_game = 2 [(buf.validate.field).required = true];
  int32 num_rounds_per_game = 3 [(buf.validate.field).required = true];
  int32 round_duration_secs = 4 [(buf.validate.field).required = true];
  int32 num_drawing_options = 5 [(buf.validate.field).required = true];
}

message CreateServerResponse {
  Server server = 1;
}

message GetServerRequest {
  string id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
}

message GetServerResponse {
  Server server = 1;
}

message GetServerByNameRequest {
  string name = 1 [(buf.validate.field).required = true];
}

message GetServerByNameResponse {
  Server server = 1;
}

message ListServersRequest {
  google.protobuf.StringValue after_id = 1;
  google.protobuf.Int32Value page_size = 2;
  ServerSortBy sort_by = 3;
  google.protobuf.Timestamp after_created_at = 4;
  google.protobuf.DoubleValue after_trending_score = 5;
  google.protobuf.Int32Value after_total_games = 6;
}

message ListServersResponse {
  repeated Server servers = 1;
  int64 total_count = 2;
  ServerSortBy sort_by = 3;
  ListServersCursor cursor = 4;
}

message ListUserServersRequest {
  string user_id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
  google.protobuf.Timestamp after_created_at = 2;
  google.protobuf.StringValue after_id = 3;
  google.protobuf.Int32Value page_size = 4;
}

message ListUserServersResponse {
  string user_id = 1;
  repeated UserServer servers = 2;
  int64 total_count = 3;
  ListServersCursor cursor = 4;
}

message GetUserServerPermissionsRequest {
  string user_id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
  string server_id = 2 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
}

message GetUserServerPermissionsResponse {
  bool is_owner = 1;
  bool is_admin = 2;
  bool has_elevated_permissions = 3;
}

message UpdateServerRequest {
  string server_id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
  google.protobuf.StringValue name = 2;
  google.protobuf.StringValue stake_per_game = 3;
  google.protobuf.Int32Value num_rounds_per_game = 4;
  google.protobuf.Int32Value round_duration_secs = 5;
  google.protobuf.Int32Value num_drawing_options = 6;
}

message UpdateServerResponse {
  Server server = 1;
}

message ArchiveServerRequest {
  string server_id = 1 [(buf.validate.field).required = true, (buf.validate.field).string.uuid = true];
}

message ArchiveServerResponse {
  Server server = 1;
}

enum ServerSortBy {
  SERVER_SORT_BY_UNSPECIFIED = 0;
  SERVER_SORT_BY_NEW = 1;
  SERVER_SORT_BY_TRENDING = 2;
  SERVER_SORT_BY_POPULAR = 3;
}

message Server {
  string id = 1;
  string name = 2;
  string owner_id = 3;
  int32 num_admins = 4;
  int32 num_custom_words = 5;
  string server_address = 6;
  string stake_per_game = 7;
  int32 num_rounds_per_game = 8;
  int32 round_duration_secs = 9;
  int32 num_drawing_options = 10;
  bool is_archived = 11;
  google.protobuf.Timestamp archived_at = 12;
  google.protobuf.Timestamp created_at = 13;
  int32 total_games = 14;
  string total_volume = 15;
  int32 total_players = 16;
  double trending_score = 17;
}

message UserServer {
  string id = 1;
  string name = 2;
  string owner_id = 3;
  int32 num_admins = 4;
  int32 num_custom_words = 5;
  string server_address = 6;
  string stake_per_game = 7;
  int32 num_rounds_per_game = 8;
  int32 round_duration_secs = 9;
  int32 num_drawing_options = 10;
  bool is_archived = 11;
  bool is_owner = 12;
  bool is_admin = 13;
  google.protobuf.Timestamp archived_at = 14;
  google.protobuf.Timestamp created_at = 15;
  int32 total_games = 16;
  string total_volume = 17;
  int32 total_players = 18;
  double trending_score = 19;
}

message ListServersCursor {
  string after_id = 1;
  int32 page_size = 2;
  google.protobuf.Timestamp after_created_at = 3;
  double after_trending_score = 4;
  int32 after_total_games = 5;
}
