syntax = "proto3";

package gameplay.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "gameplay/v1/rpc_server_service.proto";

option go_package = "github.com/spazzle-io/spazzle-api/services/gameplay/pb";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Gameplay Service";
    version: "0";
    contact: {
      name: "Spazzle";
      url: "https://spazzle.io";
    };
  };
  security_definitions: {
    security: {
      key: "bearer"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "Authorization"
        description: "Authentication token, prefixed by Bearer: bearer <token>"
      }
    }
  };
  security: {
    security_requirement: {
      key: "bearer"
    }
  };
};

service ServerService {
  rpc CreateServer(CreateServerRequest) returns (CreateServerResponse) {
    option (google.api.http) = {
      post: "/servers",
      body: "*"
    };

    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "Create server";
      description: "Create a new server";
      security: {
        security_requirement: {
          key: "bearer"
        }
      };
    };
  }

  rpc GetServer(GetServerRequest) returns (GetServerResponse) {
    option (google.api.http) = {
      get: "/servers/{id}"
    };

    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "Get server";
      description: "Get server by id";
      security: {};
    };
  }

  rpc GetServerByName(GetServerByNameRequest) returns (GetServerByNameResponse) {
    option (google.api.http) = {
      get: "/servers/by-name/{name}"
    };

    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "Get server by name";
      description: "Get server name";
      security: {};
    };
  }

  rpc ListServers(ListServersRequest) returns (ListServersResponse) {
    option (google.api.http) = {
      get: "/servers"
    };

    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "List servers";
      description: "List all servers";
      security: {};
    };
  }

  rpc ListUserServers(ListUserServersRequest) returns (ListUserServersResponse) {
    option (google.api.http) = {
      get: "/servers/by-user/{user_id}"
    };

    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      summary: "List user servers";
      description: "List servers for which a user has elevated privileges";
      security: {};
    };
  }
}
