name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: spazzle
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: set-up-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: create-databases
        run: |
          sudo apt-get install -y postgresql-client

          # Wait for postgres to be ready
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U root; then break; fi
            echo "Waiting for PostgreSQL..." && sleep 2
          done

          # Create a DB for each subdir in services/*
          for dir in services/*/; do
            db=$(basename "$dir")
            echo "Creating database: $db"
            PGPASSWORD=password psql -h localhost -U root -d postgres -c "CREATE DATABASE \"$db\";"
          done

      - name: run-tests
        run: make test short=false

      - name: upload-coverage-to-codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
